import { read as vegaRead } from 'vega';

const subtreeBreakdownCsv = `NodeLevel,NodePath,SubtreeLevel,ConceptType,
Visibility,IsSynonym,TableName,HasMetadataXML,NumberOfPaths\n
0,\\PCORI\\,1,Case,Active,N,concept_dimension,N,6\n
0,\\PCORI\\,1,Case,Active,N,concept_dimension,Y,1\n
0,\\PCORI\\,1,Case,Active,N,patient_dimension,N,1\n
0,\\PCORI\\,2,Case,Active,N,concept_dimension,N,9\n
0,\\PCORI\\,2,Case,Active,N,patient_dimension,N,3\n
0,\\PCORI\\,2,Case,Active,N,patient_dimension,Y,1\n
0,\\PCORI\\,2,Case,Active,N,visit_dimension,N,1\n
0,\\PCORI\\,2,Folder,Active,N,concept_dimension,N,7\n
0,\\PCORI\\,2,Folder,Active,N,patient_dimension,N,1\n
0,\\PCORI\\,2,Folder,Inactive,N,concept_dimension,N,6\n
0,\\PCORI\\,2,Leaf,Active,N,concept_dimension,Y,3\n
0,\\PCORI\\,2,Leaf,Hidden,N,concept_dimension,Y,23\n
0,\\PCORI\\,2,Leaf,Hidden,N,visit_dimension,Y,9\n
0,\\PCORI\\,2,Leaf,Inactive,N,concept_dimension,N,7\n
0,\\PCORI\\,2,Leaf,Inactive,N,visit_dimension,N,1\n
0,\\PCORI\\,2,Leaf,Inactive,N,visit_dimension,Y,2\n
0,\\PCORI\\,3,Case,Active,N,concept_dimension,N,47\n
0,\\PCORI\\,3,Folder,Active,N,concept_dimension,N,62\n
0,\\PCORI\\,3,Folder,Active,N,concept_dimension,Y,1\n
0,\\PCORI\\,3,Folder,Active,N,patient_dimension,N,10\n
0,\\PCORI\\,3,Folder,Active,N,visit_dimension,N,72\n
0,\\PCORI\\,3,Leaf,Active,N,concept_dimension,N,4\n
0,\\PCORI\\,3,Leaf,Active,N,concept_dimension,Y,2\n
0,\\PCORI\\,3,Leaf,Active,N,patient_dimension,N,23\n
0,\\PCORI\\,3,Leaf,Active,N,visit_dimension,N,43\n
0,\\PCORI\\,3,Leaf,Hidden,N,patient_dimension,N,1\n
0,\\PCORI\\,3,Leaf,Inactive,N,concept_dimension,N,2\n
0,\\PCORI\\,3,Leaf,Inactive,N,observation_fact,N,3\n
0,\\PCORI\\,3,Leaf,Inactive,N,patient_dimension,N,1\n
0,\\PCORI\\,3,Leaf,Inactive,N,visit_dimension,N,4\n
0,\\PCORI\\,4,Folder,Active,N,concept_dimension,N,1280\n
0,\\PCORI\\,4,Folder,Active,N,concept_dimension,Y,1\n
0,\\PCORI\\,4,Folder,Active,N,patient_dimension,N,3\n
0,\\PCORI\\,4,Folder,Active,Y,concept_dimension,N,92\n
0,\\PCORI\\,4,Folder,Inactive,N,concept_dimension,N,1\n
0,\\PCORI\\,4,Leaf,Active,N,concept_dimension,N,242\n
0,\\PCORI\\,4,Leaf,Active,N,concept_dimension,Y,4\n
0,\\PCORI\\,4,Leaf,Active,N,patient_dimension,N,107\n
0,\\PCORI\\,4,Leaf,Active,N,visit_dimension,N,1047\n
0,\\PCORI\\,4,Leaf,Active,Y,concept_dimension,N,143\n
0,\\PCORI\\,4,Leaf,Hidden,N,concept_dimension,N,1\n
0,\\PCORI\\,4,Leaf,Inactive,N,concept_dimension,N,82\n
0,\\PCORI\\,4,Leaf,Inactive,N,patient_dimension,N,67\n
0,\\PCORI\\,5,Folder,Active,N,concept_dimension,N,9270\n
0,\\PCORI\\,5,Folder,Active,N,concept_dimension,Y,69\n
0,\\PCORI\\,5,Folder,Active,N,patient_dimension,N,3\n
0,\\PCORI\\,5,Folder,Active,Y,concept_dimension,N,2882\n
0,\\PCORI\\,5,Folder,Hidden,N,concept_dimension,Y,1\n
0,\\PCORI\\,5,Folder,Inactive,N,concept_dimension,N,3\n
0,\\PCORI\\,5,Folder,Inactive,N,concept_dimension,Y,5\n
0,\\PCORI\\,5,Leaf,Active,N,concept_dimension,N,12023\n
0,\\PCORI\\,5,Leaf,Active,N,concept_dimension,Y,1\n
0,\\PCORI\\,5,Leaf,Active,N,patient_dimension,N,34\n
0,\\PCORI\\,5,Leaf,Active,Y,concept_dimension,N,4694\n
0,\\PCORI\\,5,Leaf,Active,Y,concept_dimension,Y,3\n
0,\\PCORI\\,5,Leaf,Inactive,N,concept_dimension,N,119\n
0,\\PCORI\\,5,Leaf,Inactive,Y,concept_dimension,N,66\n
0,\\PCORI\\,6,Folder,Active,N,concept_dimension,N,32678\n
0,\\PCORI\\,6,Folder,Active,N,concept_dimension,Y,1\n
0,\\PCORI\\,6,Folder,Active,Y,concept_dimension,N,4067\n
0,\\PCORI\\,6,Folder,Inactive,N,concept_dimension,N,1\n
0,\\PCORI\\,6,Leaf,Active,N,concept_dimension,N,36983\n
0,\\PCORI\\,6,Leaf,Active,N,concept_dimension,Y,268\n
0,\\PCORI\\,6,Leaf,Active,N,patient_dimension,N,94\n
0,\\PCORI\\,6,Leaf,Active,Y,concept_dimension,N,14475\n
0,\\PCORI\\,6,Leaf,Active,Y,concept_dimension,Y,258\n
0,\\PCORI\\,6,Leaf,Hidden,N,concept_dimension,Y,6\n
0,\\PCORI\\,6,Leaf,Hidden,Y,concept_dimension,Y,19\n
0,\\PCORI\\,6,Leaf,Inactive,N,concept_dimension,N,1396\n
0,\\PCORI\\,6,Leaf,Inactive,N,concept_dimension,Y,38\n
0,\\PCORI\\,6,Leaf,Inactive,Y,concept_dimension,N,2496\n
0,\\PCORI\\,6,Leaf,Inactive,Y,concept_dimension,Y,63\n
0,\\PCORI\\,7,Folder,Active,N,concept_dimension,N,56970\n
0,\\PCORI\\,7,Folder,Active,Y,concept_dimension,N,2249\n
0,\\PCORI\\,7,Leaf,Active,N,concept_dimension,N,74511\n
0,\\PCORI\\,7,Leaf,Active,N,concept_dimension,Y,9\n
0,\\PCORI\\,7,Leaf,Active,Y,concept_dimension,N,15713\n
0,\\PCORI\\,7,Leaf,Active,Y,concept_dimension,Y,54\n
0,\\PCORI\\,7,Leaf,Inactive,N,concept_dimension,N,6559\n
0,\\PCORI\\,7,Leaf,Inactive,Y,concept_dimension,N,23440\n
0,\\PCORI\\,8,Folder,Active,N,concept_dimension,N,73938\n
0,\\PCORI\\,8,Folder,Active,Y,concept_dimension,N,632\n
0,\\PCORI\\,8,Leaf,Active,N,concept_dimension,N,65790\n
0,\\PCORI\\,8,Leaf,Active,Y,concept_dimension,N,18628\n
0,\\PCORI\\,8,Leaf,Inactive,N,concept_dimension,N,5993\n
0,\\PCORI\\,8,Leaf,Inactive,Y,concept_dimension,N,9969\n
0,\\PCORI\\,9,Folder,Active,N,concept_dimension,N,102\n
0,\\PCORI\\,9,Folder,Active,Y,concept_dimension,N,20\n
0,\\PCORI\\,9,Leaf,Active,N,concept_dimension,N,111697\n
0,\\PCORI\\,9,Leaf,Active,Y,concept_dimension,N,146821\n
0,\\PCORI\\,9,Leaf,Inactive,N,concept_dimension,N,4508\n
0,\\PCORI\\,9,Leaf,Inactive,Y,concept_dimension,N,7211\n
0,\\PCORI\\,10,Leaf,Active,N,concept_dimension,N,79\n
0,\\PCORI\\,10,Leaf,Active,Y,concept_dimension,N,849\n
0,\\PCORI\\,10,Leaf,Inactive,N,concept_dimension,N,6944\n
0,\\PCORI\\,10,Leaf,Inactive,Y,concept_dimension,N,9544\n
0,\\PCORI\\,11,Leaf,Inactive,N,concept_dimension,N,19\n
1,\\PCORI\\DEMOGRAPHIC\\,2,Case,Active,N,patient_dimension,N,3\n
1,\\PCORI\\DEMOGRAPHIC\\,2,Case,Active,N,patient_dimension,Y,1\n
1,\\PCORI\\DEMOGRAPHIC\\,2,Folder,Active,N,patient_dimension,N,1\n
1,\\PCORI\\DEMOGRAPHIC\\,2,Leaf,Hidden,N,concept_dimension,Y,5\n
1,\\PCORI\\DEMOGRAPHIC\\,2,Leaf,Inactive,N,concept_dimension,N,1\n
1,\\PCORI\\DEMOGRAPHIC\\,3,Folder,Active,N,patient_dimension,N,10\n
1,\\PCORI\\DEMOGRAPHIC\\,3,Leaf,Active,N,patient_dimension,N,23\n
1,\\PCORI\\DEMOGRAPHIC\\,3,Leaf,Hidden,N,patient_dimension,N,1\n
1,\\PCORI\\DEMOGRAPHIC\\,3,Leaf,Inactive,N,patient_dimension,N,1\n
1,\\PCORI\\DEMOGRAPHIC\\,4,Folder,Active,N,patient_dimension,N,3\n
1,\\PCORI\\DEMOGRAPHIC\\,4,Leaf,Active,N,patient_dimension,N,107\n
1,\\PCORI\\DEMOGRAPHIC\\,4,Leaf,Inactive,N,patient_dimension,N,67\n
1,\\PCORI\\DEMOGRAPHIC\\,5,Folder,Active,N,patient_dimension,N,3\n
1,\\PCORI\\DEMOGRAPHIC\\,5,Leaf,Active,N,patient_dimension,N,34\n
1,\\PCORI\\DEMOGRAPHIC\\,6,Leaf,Active,N,patient_dimension,N,94\n
2,\\PCORI\\DEMOGRAPHIC\\Age\\,3,Folder,Active,N,patient_dimension,N,10\n
2,\\PCORI\\DEMOGRAPHIC\\Age\\,3,Leaf,Active,N,patient_dimension,N,1\n
2,\\PCORI\\DEMOGRAPHIC\\Age\\,4,Folder,Active,N,patient_dimension,N,3\n
2,\\PCORI\\DEMOGRAPHIC\\Age\\,4,Leaf,Active,N,patient_dimension,N,107\n
2,\\PCORI\\DEMOGRAPHIC\\Age\\,4,Leaf,Inactive,N,patient_dimension,N,67\n
2,\\PCORI\\DEMOGRAPHIC\\Age\\,5,Folder,Active,N,patient_dimension,N,3\n
2,\\PCORI\\DEMOGRAPHIC\\Age\\,5,Leaf,Active,N,patient_dimension,N,34\n
2,\\PCORI\\DEMOGRAPHIC\\Age\\,6,Leaf,Active,N,patient_dimension,N,94\n
2,\\PCORI\\DEMOGRAPHIC\\BIOBANK_FLAG\\,3,Leaf,Active,N,patient_dimension,N,1\n
2,\\PCORI\\DEMOGRAPHIC\\BIOBANK_FLAG\\,3,Leaf,Hidden,N,patient_dimension,N,1\n
2,\\PCORI\\DEMOGRAPHIC\\BIRTH_DATE\\,,,,,,,\n
2,\\PCORI\\DEMOGRAPHIC\\BIRTH_TIME\\,,,,,,,\n
2,\\PCORI\\DEMOGRAPHIC\\HISPANIC\\,3,Leaf,Active,N,patient_dimension,N,5\n
2,\\PCORI\\DEMOGRAPHIC\\HISPANIC\\,3,Leaf,Inactive,N,patient_dimension,N,1\n
2,\\PCORI\\DEMOGRAPHIC\\RACE\\,3,Leaf,Active,N,patient_dimension,N,10\n
2,\\PCORI\\DEMOGRAPHIC\\RAW_HISPANIC\\,,,,,,,\n
2,\\PCORI\\DEMOGRAPHIC\\RAW_RACE\\,,,,,,,\n
2,\\PCORI\\DEMOGRAPHIC\\RAW_SEX\\,,,,,,,\n
2,\\PCORI\\DEMOGRAPHIC\\SEX\\,3,Leaf,Active,N,patient_dimension,N,6\n
2,\\PCORI\\DEMOGRAPHIC\\VERSION\\,,,,,,,\n
1,\\PCORI\\DIAGNOSIS\\,2,Case,Active,N,concept_dimension,N,1\n
1,\\PCORI\\DIAGNOSIS\\,2,Folder,Active,N,concept_dimension,N,1\n
1,\\PCORI\\DIAGNOSIS\\,2,Folder,Inactive,N,concept_dimension,N,2\n
1,\\PCORI\\DIAGNOSIS\\,2,Leaf,Hidden,N,concept_dimension,Y,4\n
1,\\PCORI\\DIAGNOSIS\\,2,Leaf,Inactive,N,concept_dimension,N,1\n
1,\\PCORI\\DIAGNOSIS\\,3,Case,Active,N,concept_dimension,N,21\n
1,\\PCORI\\DIAGNOSIS\\,3,Folder,Active,N,concept_dimension,N,3\n
1,\\PCORI\\DIAGNOSIS\\,4,Folder,Active,N,concept_dimension,N,334\n
1,\\PCORI\\DIAGNOSIS\\,4,Folder,Active,Y,concept_dimension,N,92\n
1,\\PCORI\\DIAGNOSIS\\,4,Leaf,Active,N,concept_dimension,N,1\n
1,\\PCORI\\DIAGNOSIS\\,4,Leaf,Inactive,N,concept_dimension,N,3\n
1,\\PCORI\\DIAGNOSIS\\,5,Folder,Active,N,concept_dimension,N,2185\n
1,\\PCORI\\DIAGNOSIS\\,5,Folder,Active,Y,concept_dimension,N,1128\n
1,\\PCORI\\DIAGNOSIS\\,5,Leaf,Active,N,concept_dimension,N,136\n
1,\\PCORI\\DIAGNOSIS\\,5,Leaf,Active,Y,concept_dimension,N,56\n
1,\\PCORI\\DIAGNOSIS\\,5,Leaf,Inactive,N,concept_dimension,N,108\n
1,\\PCORI\\DIAGNOSIS\\,5,Leaf,Inactive,Y,concept_dimension,N,66\n
1,\\PCORI\\DIAGNOSIS\\,6,Folder,Active,N,concept_dimension,N,7857\n
1,\\PCORI\\DIAGNOSIS\\,6,Folder,Active,Y,concept_dimension,N,3960\n
1,\\PCORI\\DIAGNOSIS\\,6,Leaf,Active,N,concept_dimension,N,4800\n
1,\\PCORI\\DIAGNOSIS\\,6,Leaf,Active,Y,concept_dimension,N,1963\n
1,\\PCORI\\DIAGNOSIS\\,6,Leaf,Inactive,N,concept_dimension,N,1396\n
1,\\PCORI\\DIAGNOSIS\\,6,Leaf,Inactive,Y,concept_dimension,N,2486\n
1,\\PCORI\\DIAGNOSIS\\,7,Folder,Active,N,concept_dimension,N,9596\n
1,\\PCORI\\DIAGNOSIS\\,7,Folder,Active,Y,concept_dimension,N,2114\n
1,\\PCORI\\DIAGNOSIS\\,7,Leaf,Active,N,concept_dimension,N,13401\n
1,\\PCORI\\DIAGNOSIS\\,7,Leaf,Active,Y,concept_dimension,N,1050\n
1,\\PCORI\\DIAGNOSIS\\,7,Leaf,Inactive,N,concept_dimension,N,6559\n
1,\\PCORI\\DIAGNOSIS\\,7,Leaf,Inactive,Y,concept_dimension,N,23440\n
1,\\PCORI\\DIAGNOSIS\\,8,Folder,Active,N,concept_dimension,N,9513\n
1,\\PCORI\\DIAGNOSIS\\,8,Folder,Active,Y,concept_dimension,N,592\n
1,\\PCORI\\DIAGNOSIS\\,8,Leaf,Active,N,concept_dimension,N,22945\n
1,\\PCORI\\DIAGNOSIS\\,8,Leaf,Active,Y,concept_dimension,N,498\n
1,\\PCORI\\DIAGNOSIS\\,8,Leaf,Inactive,N,concept_dimension,N,5993\n
1,\\PCORI\\DIAGNOSIS\\,8,Leaf,Inactive,Y,concept_dimension,N,9969\n
1,\\PCORI\\DIAGNOSIS\\,9,Folder,Active,N,concept_dimension,N,61\n
1,\\PCORI\\DIAGNOSIS\\,9,Leaf,Active,N,concept_dimension,N,39047\n
1,\\PCORI\\DIAGNOSIS\\,9,Leaf,Inactive,N,concept_dimension,N,4508\n
1,\\PCORI\\DIAGNOSIS\\,9,Leaf,Inactive,Y,concept_dimension,N,7211\n
1,\\PCORI\\DIAGNOSIS\\,10,Leaf,Inactive,N,concept_dimension,N,6944\n
1,\\PCORI\\DIAGNOSIS\\,10,Leaf,Inactive,Y,concept_dimension,N,9544\n
1,\\PCORI\\DIAGNOSIS\\,11,Leaf,Inactive,N,concept_dimension,N,19\n
2,\\PCORI\\DIAGNOSIS\\09\\,3,Folder,Active,N,concept_dimension,N,3\n
2,\\PCORI\\DIAGNOSIS\\09\\,4,Folder,Active,N,concept_dimension,N,55\n
2,\\PCORI\\DIAGNOSIS\\09\\,4,Leaf,Active,N,concept_dimension,N,1\n
2,\\PCORI\\DIAGNOSIS\\09\\,5,Folder,Active,N,concept_dimension,N,364\n
2,\\PCORI\\DIAGNOSIS\\09\\,5,Leaf,Active,N,concept_dimension,N,54\n
2,\\PCORI\\DIAGNOSIS\\09\\,6,Folder,Active,N,concept_dimension,N,1036\n
2,\\PCORI\\DIAGNOSIS\\09\\,6,Leaf,Active,N,concept_dimension,N,1597\n
2,\\PCORI\\DIAGNOSIS\\09\\,7,Folder,Active,N,concept_dimension,N,1591\n
2,\\PCORI\\DIAGNOSIS\\09\\,7,Leaf,Active,N,concept_dimension,N,4882\n
2,\\PCORI\\DIAGNOSIS\\09\\,8,Folder,Active,N,concept_dimension,N,145\n
2,\\PCORI\\DIAGNOSIS\\09\\,8,Leaf,Active,N,concept_dimension,N,7268\n
2,\\PCORI\\DIAGNOSIS\\09\\,9,Leaf,Active,N,concept_dimension,N,867\n
2,\\PCORI\\DIAGNOSIS\\10\\,3,Case,Active,N,concept_dimension,N,21\n
2,\\PCORI\\DIAGNOSIS\\10\\,4,Folder,Active,N,concept_dimension,N,279\n
2,\\PCORI\\DIAGNOSIS\\10\\,4,Folder,Active,Y,concept_dimension,N,92\n
2,\\PCORI\\DIAGNOSIS\\10\\,4,Leaf,Inactive,N,concept_dimension,N,3\n
2,\\PCORI\\DIAGNOSIS\\10\\,5,Folder,Active,N,concept_dimension,N,1821\n
2,\\PCORI\\DIAGNOSIS\\10\\,5,Folder,Active,Y,concept_dimension,N,1128\n
2,\\PCORI\\DIAGNOSIS\\10\\,5,Leaf,Active,N,concept_dimension,N,82\n
2,\\PCORI\\DIAGNOSIS\\10\\,5,Leaf,Active,Y,concept_dimension,N,56\n
2,\\PCORI\\DIAGNOSIS\\10\\,5,Leaf,Inactive,N,concept_dimension,N,108\n
2,\\PCORI\\DIAGNOSIS\\10\\,5,Leaf,Inactive,Y,concept_dimension,N,66\n
2,\\PCORI\\DIAGNOSIS\\10\\,6,Folder,Active,N,concept_dimension,N,6821\n
2,\\PCORI\\DIAGNOSIS\\10\\,6,Folder,Active,Y,concept_dimension,N,3960\n
2,\\PCORI\\DIAGNOSIS\\10\\,6,Leaf,Active,N,concept_dimension,N,3203\n
2,\\PCORI\\DIAGNOSIS\\10\\,6,Leaf,Active,Y,concept_dimension,N,1963\n
2,\\PCORI\\DIAGNOSIS\\10\\,6,Leaf,Inactive,N,concept_dimension,N,1396\n
2,\\PCORI\\DIAGNOSIS\\10\\,6,Leaf,Inactive,Y,concept_dimension,N,2486\n
2,\\PCORI\\DIAGNOSIS\\10\\,7,Folder,Active,N,concept_dimension,N,8005\n
2,\\PCORI\\DIAGNOSIS\\10\\,7,Folder,Active,Y,concept_dimension,N,2114\n
2,\\PCORI\\DIAGNOSIS\\10\\,7,Leaf,Active,N,concept_dimension,N,8519\n
2,\\PCORI\\DIAGNOSIS\\10\\,7,Leaf,Active,Y,concept_dimension,N,1050\n
2,\\PCORI\\DIAGNOSIS\\10\\,7,Leaf,Inactive,N,concept_dimension,N,6559\n
2,\\PCORI\\DIAGNOSIS\\10\\,7,Leaf,Inactive,Y,concept_dimension,N,23440\n
2,\\PCORI\\DIAGNOSIS\\10\\,8,Folder,Active,N,concept_dimension,N,9368\n
2,\\PCORI\\DIAGNOSIS\\10\\,8,Folder,Active,Y,concept_dimension,N,592\n
2,\\PCORI\\DIAGNOSIS\\10\\,8,Leaf,Active,N,concept_dimension,N,15677\n
2,\\PCORI\\DIAGNOSIS\\10\\,8,Leaf,Active,Y,concept_dimension,N,498\n
2,\\PCORI\\DIAGNOSIS\\10\\,8,Leaf,Inactive,N,concept_dimension,N,5993\n
2,\\PCORI\\DIAGNOSIS\\10\\,8,Leaf,Inactive,Y,concept_dimension,N,9969\n
2,\\PCORI\\DIAGNOSIS\\10\\,9,Folder,Active,N,concept_dimension,N,61\n
2,\\PCORI\\DIAGNOSIS\\10\\,9,Leaf,Active,N,concept_dimension,N,38180\n
2,\\PCORI\\DIAGNOSIS\\10\\,9,Leaf,Inactive,N,concept_dimension,N,4508\n
2,\\PCORI\\DIAGNOSIS\\10\\,9,Leaf,Inactive,Y,concept_dimension,N,7211\n
2,\\PCORI\\DIAGNOSIS\\10\\,10,Leaf,Inactive,N,concept_dimension,N,6944\n
2,\\PCORI\\DIAGNOSIS\\10\\,10,Leaf,Inactive,Y,concept_dimension,N,9544\n
2,\\PCORI\\DIAGNOSIS\\10\\,11,Leaf,Inactive,N,concept_dimension,N,19\n
2,\\PCORI\\DIAGNOSIS\\11\\,,,,,,,\n
2,\\PCORI\\DIAGNOSIS\\RAW_DX\\,,,,,,,\n
2,\\PCORI\\DIAGNOSIS\\RAW_DX_SOURCE\\,,,,,,,\n
2,\\PCORI\\DIAGNOSIS\\RAW_DX_TYPE\\,,,,,,,\n
2,\\PCORI\\DIAGNOSIS\\RAW_PDX\\,,,,,,,\n
2,\\PCORI\\DIAGNOSIS\\SM\\,,,,,,,\n
2,\\PCORI\\DIAGNOSIS\\VERSION\\,,,,,,,\n
1,\\PCORI\\ENCOUNTER\\,2,Case,Active,N,concept_dimension,N,5\n
1,\\PCORI\\ENCOUNTER\\,2,Case,Active,N,visit_dimension,N,1\n
1,\\PCORI\\ENCOUNTER\\,2,Folder,Active,N,concept_dimension,N,1\n
1,\\PCORI\\ENCOUNTER\\,2,Leaf,Hidden,N,visit_dimension,Y,9\n
1,\\PCORI\\ENCOUNTER\\,2,Leaf,Inactive,N,visit_dimension,N,1\n
1,\\PCORI\\ENCOUNTER\\,2,Leaf,Inactive,N,visit_dimension,Y,2\n
1,\\PCORI\\ENCOUNTER\\,3,Folder,Active,N,concept_dimension,N,2\n
1,\\PCORI\\ENCOUNTER\\,3,Folder,Active,N,visit_dimension,N,72\n
1,\\PCORI\\ENCOUNTER\\,3,Leaf,Active,N,concept_dimension,N,2\n
1,\\PCORI\\ENCOUNTER\\,3,Leaf,Active,N,visit_dimension,N,42\n
1,\\PCORI\\ENCOUNTER\\,3,Leaf,Inactive,N,concept_dimension,N,1\n
1,\\PCORI\\ENCOUNTER\\,3,Leaf,Inactive,N,visit_dimension,N,4\n
1,\\PCORI\\ENCOUNTER\\,4,Folder,Active,N,concept_dimension,N,54\n
1,\\PCORI\\ENCOUNTER\\,4,Leaf,Active,N,visit_dimension,N,1047\n
1,\\PCORI\\ENCOUNTER\\,5,Folder,Active,N,concept_dimension,N,51\n
1,\\PCORI\\ENCOUNTER\\,5,Leaf,Active,N,concept_dimension,N,749\n
1,\\PCORI\\ENCOUNTER\\,6,Folder,Active,N,concept_dimension,N,2\n
1,\\PCORI\\ENCOUNTER\\,6,Leaf,Active,N,concept_dimension,N,659\n
1,\\PCORI\\ENCOUNTER\\,7,Leaf,Active,N,concept_dimension,N,4\n
2,\\PCORI\\ENCOUNTER\\ADMIT_DATE\\,,,,,,,\n
2,\\PCORI\\ENCOUNTER\\ADMIT_TIME\\,,,,,,,\n
2,\\PCORI\\ENCOUNTER\\ADMITTING_SOURCE\\,3,Leaf,Active,N,visit_dimension,N,14\n
2,\\PCORI\\ENCOUNTER\\ADMITTING_SOURCE\\,3,Leaf,Inactive,N,visit_dimension,N,1\n
2,\\PCORI\\ENCOUNTER\\Age at visit\\,3,Folder,Active,N,visit_dimension,N,10\n
2,\\PCORI\\ENCOUNTER\\Age at visit\\,4,Leaf,Active,N,visit_dimension,N,110\n
2,\\PCORI\\ENCOUNTER\\DISCHARGE_DATE\\,,,,,,,\n
2,\\PCORI\\ENCOUNTER\\DISCHARGE_DISPOSITION\\,3,Leaf,Active,N,visit_dimension,N,4\n
2,\\PCORI\\ENCOUNTER\\DISCHARGE_DISPOSITION\\,3,Leaf,Inactive,N,visit_dimension,N,1\n
2,\\PCORI\\ENCOUNTER\\DISCHARGE_STATUS\\,3,Leaf,Active,N,visit_dimension,N,16\n
2,\\PCORI\\ENCOUNTER\\DISCHARGE_STATUS\\,3,Leaf,Inactive,N,visit_dimension,N,1\n
2,\\PCORI\\ENCOUNTER\\DISCHARGE_TIME\\,,,,,,,\n
2,\\PCORI\\ENCOUNTER\\DRG\\,3,Folder,Active,N,concept_dimension,N,2\n
2,\\PCORI\\ENCOUNTER\\DRG\\,3,Leaf,Active,N,concept_dimension,N,2\n
2,\\PCORI\\ENCOUNTER\\DRG\\,3,Leaf,Inactive,N,concept_dimension,N,1\n
2,\\PCORI\\ENCOUNTER\\DRG\\,4,Folder,Active,N,concept_dimension,N,54\n
2,\\PCORI\\ENCOUNTER\\DRG\\,5,Folder,Active,N,concept_dimension,N,51\n
2,\\PCORI\\ENCOUNTER\\DRG\\,5,Leaf,Active,N,concept_dimension,N,749\n
2,\\PCORI\\ENCOUNTER\\DRG\\,6,Folder,Active,N,concept_dimension,N,2\n
2,\\PCORI\\ENCOUNTER\\DRG\\,6,Leaf,Active,N,concept_dimension,N,659\n
2,\\PCORI\\ENCOUNTER\\DRG\\,7,Leaf,Active,N,concept_dimension,N,4\n
2,\\PCORI\\ENCOUNTER\\ENC_TYPE\\,3,Leaf,Active,N,visit_dimension,N,8\n
2,\\PCORI\\ENCOUNTER\\ENC_TYPE\\,3,Leaf,Inactive,N,visit_dimension,N,1\n
2,\\PCORI\\ENCOUNTER\\FACILITY_LOCATION\\,3,Folder,Active,N,visit_dimension,N,62\n
2,\\PCORI\\ENCOUNTER\\FACILITY_LOCATION\\,4,Leaf,Active,N,visit_dimension,N,937\n
2,\\PCORI\\ENCOUNTER\\FACILITYID\\,,,,,,,\n
2,\\PCORI\\ENCOUNTER\\PROVIDERID\\,,,,,,,\n
2,\\PCORI\\ENCOUNTER\\RAW_ADMITTING_SOURCE\\,,,,,,,\n
2,\\PCORI\\ENCOUNTER\\RAW_DISCHARGE_DISPOSITION\\,,,,,,,\n
2,\\PCORI\\ENCOUNTER\\RAW_DISCHARGE_STATUS\\,,,,,,,\n
2,\\PCORI\\ENCOUNTER\\RAW_DRG_TYPE\\,,,,,,,\n
2,\\PCORI\\ENCOUNTER\\RAW_ENC_TYPE\\,,,,,,,\n
2,\\PCORI\\ENCOUNTER\\VERSION\\,,,,,,,\n
1,\\PCORI\\ENROLLMENT\\,2,Case,Active,N,concept_dimension,N,1\n
1,\\PCORI\\ENROLLMENT\\,2,Leaf,Hidden,N,concept_dimension,Y,2\n
1,\\PCORI\\ENROLLMENT\\,2,Leaf,Inactive,N,concept_dimension,N,1\n
1,\\PCORI\\ENROLLMENT\\,3,Leaf,Active,N,visit_dimension,N,1\n
1,\\PCORI\\ENROLLMENT\\,3,Leaf,Inactive,N,observation_fact,N,3\n
2,\\PCORI\\ENROLLMENT\\ENR_BASIS\\,3,Leaf,Active,N,visit_dimension,N,1\n
2,\\PCORI\\ENROLLMENT\\ENR_BASIS\\,3,Leaf,Inactive,N,observation_fact,N,3\n
2,\\PCORI\\ENROLLMENT\\ENR_END_DATE\\,,,,,,,\n
2,\\PCORI\\ENROLLMENT\\ENR_START_DATE\\,,,,,,,\n
2,\\PCORI\\ENROLLMENT\\VERSION\\,,,,,,,\n
1,\\PCORI\\LAB_RESULT_CM\\,2,Folder,Active,N,concept_dimension,N,1\n
1,\\PCORI\\LAB_RESULT_CM\\,2,Leaf,Inactive,N,concept_dimension,N,1\n
1,\\PCORI\\LAB_RESULT_CM\\,3,Folder,Active,N,concept_dimension,N,5\n
1,\\PCORI\\LAB_RESULT_CM\\,3,Folder,Active,N,concept_dimension,Y,1\n
1,\\PCORI\\LAB_RESULT_CM\\,4,Folder,Active,N,concept_dimension,N,17\n
1,\\PCORI\\LAB_RESULT_CM\\,4,Folder,Active,N,concept_dimension,Y,1\n
1,\\PCORI\\LAB_RESULT_CM\\,4,Folder,Inactive,N,concept_dimension,N,1\n
1,\\PCORI\\LAB_RESULT_CM\\,4,Leaf,Active,N,concept_dimension,Y,4\n
1,\\PCORI\\LAB_RESULT_CM\\,5,Folder,Active,N,concept_dimension,N,3\n
1,\\PCORI\\LAB_RESULT_CM\\,5,Folder,Active,N,concept_dimension,Y,69\n
1,\\PCORI\\LAB_RESULT_CM\\,5,Folder,Hidden,N,concept_dimension,Y,1\n
1,\\PCORI\\LAB_RESULT_CM\\,5,Folder,Inactive,N,concept_dimension,N,3\n
1,\\PCORI\\LAB_RESULT_CM\\,5,Folder,Inactive,N,concept_dimension,Y,5\n
1,\\PCORI\\LAB_RESULT_CM\\,5,Leaf,Active,N,concept_dimension,Y,1\n
1,\\PCORI\\LAB_RESULT_CM\\,5,Leaf,Active,Y,concept_dimension,Y,3\n
1,\\PCORI\\LAB_RESULT_CM\\,6,Folder,Active,N,concept_dimension,N,8\n
1,\\PCORI\\LAB_RESULT_CM\\,6,Folder,Active,N,concept_dimension,Y,1\n
1,\\PCORI\\LAB_RESULT_CM\\,6,Leaf,Active,N,concept_dimension,N,46\n
1,\\PCORI\\LAB_RESULT_CM\\,6,Leaf,Active,N,concept_dimension,Y,268\n
1,\\PCORI\\LAB_RESULT_CM\\,6,Leaf,Active,Y,concept_dimension,N,46\n
1,\\PCORI\\LAB_RESULT_CM\\,6,Leaf,Active,Y,concept_dimension,Y,258\n
1,\\PCORI\\LAB_RESULT_CM\\,6,Leaf,Hidden,N,concept_dimension,Y,6\n
1,\\PCORI\\LAB_RESULT_CM\\,6,Leaf,Hidden,Y,concept_dimension,Y,19\n
1,\\PCORI\\LAB_RESULT_CM\\,6,Leaf,Inactive,N,concept_dimension,Y,38\n
1,\\PCORI\\LAB_RESULT_CM\\,6,Leaf,Inactive,Y,concept_dimension,N,10\n
1,\\PCORI\\LAB_RESULT_CM\\,6,Leaf,Inactive,Y,concept_dimension,Y,63\n
1,\\PCORI\\LAB_RESULT_CM\\,7,Leaf,Active,N,concept_dimension,N,16\n
1,\\PCORI\\LAB_RESULT_CM\\,7,Leaf,Active,N,concept_dimension,Y,9\n
1,\\PCORI\\LAB_RESULT_CM\\,7,Leaf,Active,Y,concept_dimension,N,135\n
1,\\PCORI\\LAB_RESULT_CM\\,7,Leaf,Active,Y,concept_dimension,Y,54\n
2,\\PCORI\\LAB_RESULT_CM\\LAB_NAME\\,3,Folder,Active,N,concept_dimension,N,5\n
2,\\PCORI\\LAB_RESULT_CM\\LAB_NAME\\,3,Folder,Active,N,concept_dimension,Y,1\n
2,\\PCORI\\LAB_RESULT_CM\\LAB_NAME\\,4,Folder,Active,N,concept_dimension,N,17\n
2,\\PCORI\\LAB_RESULT_CM\\LAB_NAME\\,4,Folder,Active,N,concept_dimension,Y,1\n
2,\\PCORI\\LAB_RESULT_CM\\LAB_NAME\\,4,Folder,Inactive,N,concept_dimension,N,1\n
2,\\PCORI\\LAB_RESULT_CM\\LAB_NAME\\,4,Leaf,Active,N,concept_dimension,Y,4\n
2,\\PCORI\\LAB_RESULT_CM\\LAB_NAME\\,5,Folder,Active,N,concept_dimension,N,3\n
2,\\PCORI\\LAB_RESULT_CM\\LAB_NAME\\,5,Folder,Active,N,concept_dimension,Y,69\n
2,\\PCORI\\LAB_RESULT_CM\\LAB_NAME\\,5,Folder,Hidden,N,concept_dimension,Y,1\n
2,\\PCORI\\LAB_RESULT_CM\\LAB_NAME\\,5,Folder,Inactive,N,concept_dimension,N,3\n
2,\\PCORI\\LAB_RESULT_CM\\LAB_NAME\\,5,Folder,Inactive,N,concept_dimension,Y,5\n
2,\\PCORI\\LAB_RESULT_CM\\LAB_NAME\\,5,Leaf,Active,N,concept_dimension,Y,1\n
2,\\PCORI\\LAB_RESULT_CM\\LAB_NAME\\,5,Leaf,Active,Y,concept_dimension,Y,3\n
2,\\PCORI\\LAB_RESULT_CM\\LAB_NAME\\,6,Folder,Active,N,concept_dimension,N,8\n
2,\\PCORI\\LAB_RESULT_CM\\LAB_NAME\\,6,Folder,Active,N,concept_dimension,Y,1\n
2,\\PCORI\\LAB_RESULT_CM\\LAB_NAME\\,6,Leaf,Active,N,concept_dimension,N,46\n
2,\\PCORI\\LAB_RESULT_CM\\LAB_NAME\\,6,Leaf,Active,N,concept_dimension,Y,268\n
2,\\PCORI\\LAB_RESULT_CM\\LAB_NAME\\,6,Leaf,Active,Y,concept_dimension,N,46\n
2,\\PCORI\\LAB_RESULT_CM\\LAB_NAME\\,6,Leaf,Active,Y,concept_dimension,Y,258\n
2,\\PCORI\\LAB_RESULT_CM\\LAB_NAME\\,6,Leaf,Hidden,N,concept_dimension,Y,6\n
2,\\PCORI\\LAB_RESULT_CM\\LAB_NAME\\,6,Leaf,Hidden,Y,concept_dimension,Y,19\n
2,\\PCORI\\LAB_RESULT_CM\\LAB_NAME\\,6,Leaf,Inactive,N,concept_dimension,Y,38\n
2,\\PCORI\\LAB_RESULT_CM\\LAB_NAME\\,6,Leaf,Inactive,Y,concept_dimension,N,10\n
2,\\PCORI\\LAB_RESULT_CM\\LAB_NAME\\,6,Leaf,Inactive,Y,concept_dimension,Y,63\n
2,\\PCORI\\LAB_RESULT_CM\\LAB_NAME\\,7,Leaf,Active,N,concept_dimension,N,16\n
2,\\PCORI\\LAB_RESULT_CM\\LAB_NAME\\,7,Leaf,Active,N,concept_dimension,Y,9\n
2,\\PCORI\\LAB_RESULT_CM\\LAB_NAME\\,7,Leaf,Active,Y,concept_dimension,N,135\n
2,\\PCORI\\LAB_RESULT_CM\\LAB_NAME\\,7,Leaf,Active,Y,concept_dimension,Y,54\n
2,\\PCORI\\LAB_RESULT_CM\\VERSION\\,,,,,,,\n
1,\\PCORI\\MEDICATION\\,2,Case,Active,N,concept_dimension,N,1\n
1,\\PCORI\\MEDICATION\\,2,Leaf,Hidden,N,concept_dimension,Y,8\n
1,\\PCORI\\MEDICATION\\,2,Leaf,Inactive,N,concept_dimension,N,1\n
1,\\PCORI\\MEDICATION\\,3,Folder,Active,N,concept_dimension,N,32\n
1,\\PCORI\\MEDICATION\\,4,Folder,Active,N,concept_dimension,N,475\n
1,\\PCORI\\MEDICATION\\,4,Leaf,Active,N,concept_dimension,N,125\n
1,\\PCORI\\MEDICATION\\,4,Leaf,Inactive,N,concept_dimension,N,79\n
1,\\PCORI\\MEDICATION\\,5,Folder,Active,N,concept_dimension,N,4860\n
1,\\PCORI\\MEDICATION\\,5,Leaf,Active,N,concept_dimension,N,8557\n
1,\\PCORI\\MEDICATION\\,5,Leaf,Inactive,N,concept_dimension,N,11\n
1,\\PCORI\\MEDICATION\\,6,Folder,Active,N,concept_dimension,N,12462\n
1,\\PCORI\\MEDICATION\\,6,Folder,Inactive,N,concept_dimension,N,1\n
1,\\PCORI\\MEDICATION\\,6,Leaf,Active,N,concept_dimension,N,22543\n
1,\\PCORI\\MEDICATION\\,7,Folder,Active,N,concept_dimension,N,13296\n
1,\\PCORI\\MEDICATION\\,7,Leaf,Active,N,concept_dimension,N,56253\n
1,\\PCORI\\MEDICATION\\,8,Folder,Active,N,concept_dimension,N,2962\n
1,\\PCORI\\MEDICATION\\,8,Leaf,Active,N,concept_dimension,N,38995\n
1,\\PCORI\\MEDICATION\\,9,Leaf,Active,N,concept_dimension,N,39\n
2,\\PCORI\\MEDICATION\\RAW_RX_FREQUENCY\\,,,,,,,\n
2,\\PCORI\\MEDICATION\\RAW_RX_MED_NAME\\,,,,,,,\n
2,\\PCORI\\MEDICATION\\RAW_RXNORM_CUI\\,,,,,,,\n
2,\\PCORI\\MEDICATION\\RX_END_DATE\\,,,,,,,\n
2,\\PCORI\\MEDICATION\\RX_ORDER_DATE\\,,,,,,,\n
2,\\PCORI\\MEDICATION\\RX_ORDER_TIME\\,,,,,,,\n
2,\\PCORI\\MEDICATION\\RX_PROVIDERID\\,,,,,,,\n
2,\\PCORI\\MEDICATION\\RX_START_DATE\\,,,,,,,\n
2,\\PCORI\\MEDICATION\\RXNORM_CUI\\,3,Folder,Active,N,concept_dimension,N,32\n
2,\\PCORI\\MEDICATION\\RXNORM_CUI\\,4,Folder,Active,N,concept_dimension,N,475\n
2,\\PCORI\\MEDICATION\\RXNORM_CUI\\,4,Leaf,Active,N,concept_dimension,N,125\n
2,\\PCORI\\MEDICATION\\RXNORM_CUI\\,4,Leaf,Inactive,N,concept_dimension,N,79\n
2,\\PCORI\\MEDICATION\\RXNORM_CUI\\,5,Folder,Active,N,concept_dimension,N,4860\n
2,\\PCORI\\MEDICATION\\RXNORM_CUI\\,5,Leaf,Active,N,concept_dimension,N,8557\n
2,\\PCORI\\MEDICATION\\RXNORM_CUI\\,5,Leaf,Inactive,N,concept_dimension,N,11\n
2,\\PCORI\\MEDICATION\\RXNORM_CUI\\,6,Folder,Active,N,concept_dimension,N,12462\n
2,\\PCORI\\MEDICATION\\RXNORM_CUI\\,6,Folder,Inactive,N,concept_dimension,N,1\n
2,\\PCORI\\MEDICATION\\RXNORM_CUI\\,6,Leaf,Active,N,concept_dimension,N,22543\n
2,\\PCORI\\MEDICATION\\RXNORM_CUI\\,7,Folder,Active,N,concept_dimension,N,13296\n
2,\\PCORI\\MEDICATION\\RXNORM_CUI\\,7,Leaf,Active,N,concept_dimension,N,56253\n
2,\\PCORI\\MEDICATION\\RXNORM_CUI\\,8,Folder,Active,N,concept_dimension,N,2962\n
2,\\PCORI\\MEDICATION\\RXNORM_CUI\\,8,Leaf,Active,N,concept_dimension,N,38995\n
2,\\PCORI\\MEDICATION\\RXNORM_CUI\\,9,Leaf,Active,N,concept_dimension,N,39\n
2,\\PCORI\\MEDICATION\\VERSION\\,,,,,,,\n
1,\\PCORI\\PROCEDURE\\,2,Case,Active,N,concept_dimension,N,1\n
1,\\PCORI\\PROCEDURE\\,2,Folder,Active,N,concept_dimension,N,2\n
1,\\PCORI\\PROCEDURE\\,2,Folder,Inactive,N,concept_dimension,N,4\n
1,\\PCORI\\PROCEDURE\\,2,Leaf,Inactive,N,concept_dimension,N,1\n
1,\\PCORI\\PROCEDURE\\,3,Case,Active,N,concept_dimension,N,24\n
1,\\PCORI\\PROCEDURE\\,3,Folder,Active,N,concept_dimension,N,19\n
1,\\PCORI\\PROCEDURE\\,4,Folder,Active,N,concept_dimension,N,399\n
1,\\PCORI\\PROCEDURE\\,4,Leaf,Active,N,concept_dimension,N,110\n
1,\\PCORI\\PROCEDURE\\,4,Leaf,Active,Y,concept_dimension,N,143\n
1,\\PCORI\\PROCEDURE\\,5,Folder,Active,N,concept_dimension,N,2171\n
1,\\PCORI\\PROCEDURE\\,5,Folder,Active,Y,concept_dimension,N,1754\n
1,\\PCORI\\PROCEDURE\\,5,Leaf,Active,N,concept_dimension,N,2576\n
1,\\PCORI\\PROCEDURE\\,5,Leaf,Active,Y,concept_dimension,N,4638\n
1,\\PCORI\\PROCEDURE\\,6,Folder,Active,N,concept_dimension,N,12349\n
1,\\PCORI\\PROCEDURE\\,6,Folder,Active,Y,concept_dimension,N,107\n
1,\\PCORI\\PROCEDURE\\,6,Leaf,Active,N,concept_dimension,N,8935\n
1,\\PCORI\\PROCEDURE\\,6,Leaf,Active,Y,concept_dimension,N,12466\n
1,\\PCORI\\PROCEDURE\\,7,Folder,Active,N,concept_dimension,N,34078\n
1,\\PCORI\\PROCEDURE\\,7,Folder,Active,Y,concept_dimension,N,135\n
1,\\PCORI\\PROCEDURE\\,7,Leaf,Active,N,concept_dimension,N,4837\n
1,\\PCORI\\PROCEDURE\\,7,Leaf,Active,Y,concept_dimension,N,14528\n
1,\\PCORI\\PROCEDURE\\,8,Folder,Active,N,concept_dimension,N,61463\n
1,\\PCORI\\PROCEDURE\\,8,Folder,Active,Y,concept_dimension,N,40\n
1,\\PCORI\\PROCEDURE\\,8,Leaf,Active,N,concept_dimension,N,3850\n
1,\\PCORI\\PROCEDURE\\,8,Leaf,Active,Y,concept_dimension,N,18130\n
1,\\PCORI\\PROCEDURE\\,9,Folder,Active,N,concept_dimension,N,41\n
1,\\PCORI\\PROCEDURE\\,9,Folder,Active,Y,concept_dimension,N,20\n
1,\\PCORI\\PROCEDURE\\,9,Leaf,Active,N,concept_dimension,N,72611\n
1,\\PCORI\\PROCEDURE\\,9,Leaf,Active,Y,concept_dimension,N,146821\n
1,\\PCORI\\PROCEDURE\\,10,Leaf,Active,N,concept_dimension,N,79\n
1,\\PCORI\\PROCEDURE\\,10,Leaf,Active,Y,concept_dimension,N,849\n
2,\\PCORI\\PROCEDURE\\09\\,3,Folder,Active,N,concept_dimension,N,18\n
2,\\PCORI\\PROCEDURE\\09\\,4,Folder,Active,N,concept_dimension,N,109\n
2,\\PCORI\\PROCEDURE\\09\\,5,Folder,Active,N,concept_dimension,N,659\n
2,\\PCORI\\PROCEDURE\\09\\,5,Leaf,Active,N,concept_dimension,N,295\n
2,\\PCORI\\PROCEDURE\\09\\,6,Leaf,Active,N,concept_dimension,N,3583\n
2,\\PCORI\\PROCEDURE\\10\\,3,Case,Active,N,concept_dimension,N,16\n
2,\\PCORI\\PROCEDURE\\10\\,4,Folder,Active,N,concept_dimension,N,102\n
2,\\PCORI\\PROCEDURE\\10\\,5,Folder,Active,N,concept_dimension,N,845\n
2,\\PCORI\\PROCEDURE\\10\\,5,Folder,Active,Y,concept_dimension,N,1690\n
2,\\PCORI\\PROCEDURE\\10\\,6,Folder,Active,N,concept_dimension,N,11304\n
2,\\PCORI\\PROCEDURE\\10\\,7,Folder,Active,N,concept_dimension,N,32727\n
2,\\PCORI\\PROCEDURE\\10\\,8,Folder,Active,N,concept_dimension,N,61271\n
2,\\PCORI\\PROCEDURE\\10\\,9,Leaf,Active,N,concept_dimension,N,71924\n
2,\\PCORI\\PROCEDURE\\10\\,9,Leaf,Active,Y,concept_dimension,N,143848\n
2,\\PCORI\\PROCEDURE\\11\\,,,,,,,\n
2,\\PCORI\\PROCEDURE\\CH\\,3,Case,Active,N,concept_dimension,N,8\n
2,\\PCORI\\PROCEDURE\\CH\\,3,Folder,Active,N,concept_dimension,N,1\n
2,\\PCORI\\PROCEDURE\\CH\\,4,Folder,Active,N,concept_dimension,N,188\n
2,\\PCORI\\PROCEDURE\\CH\\,4,Leaf,Active,N,concept_dimension,N,110\n
2,\\PCORI\\PROCEDURE\\CH\\,4,Leaf,Active,Y,concept_dimension,N,143\n
2,\\PCORI\\PROCEDURE\\CH\\,5,Folder,Active,N,concept_dimension,N,667\n
2,\\PCORI\\PROCEDURE\\CH\\,5,Folder,Active,Y,concept_dimension,N,64\n
2,\\PCORI\\PROCEDURE\\CH\\,5,Leaf,Active,N,concept_dimension,N,2281\n
2,\\PCORI\\PROCEDURE\\CH\\,5,Leaf,Active,Y,concept_dimension,N,4638\n
2,\\PCORI\\PROCEDURE\\CH\\,6,Folder,Active,N,concept_dimension,N,1045\n
2,\\PCORI\\PROCEDURE\\CH\\,6,Folder,Active,Y,concept_dimension,N,107\n
2,\\PCORI\\PROCEDURE\\CH\\,6,Leaf,Active,N,concept_dimension,N,5352\n
2,\\PCORI\\PROCEDURE\\CH\\,6,Leaf,Active,Y,concept_dimension,N,12466\n
2,\\PCORI\\PROCEDURE\\CH\\,7,Folder,Active,N,concept_dimension,N,1351\n
2,\\PCORI\\PROCEDURE\\CH\\,7,Folder,Active,Y,concept_dimension,N,135\n
2,\\PCORI\\PROCEDURE\\CH\\,7,Leaf,Active,N,concept_dimension,N,4837\n
2,\\PCORI\\PROCEDURE\\CH\\,7,Leaf,Active,Y,concept_dimension,N,14528\n
2,\\PCORI\\PROCEDURE\\CH\\,8,Folder,Active,N,concept_dimension,N,192\n
2,\\PCORI\\PROCEDURE\\CH\\,8,Folder,Active,Y,concept_dimension,N,40\n
2,\\PCORI\\PROCEDURE\\CH\\,8,Leaf,Active,N,concept_dimension,N,3850\n
2,\\PCORI\\PROCEDURE\\CH\\,8,Leaf,Active,Y,concept_dimension,N,18130\n
2,\\PCORI\\PROCEDURE\\CH\\,9,Folder,Active,N,concept_dimension,N,41\n
2,\\PCORI\\PROCEDURE\\CH\\,9,Folder,Active,Y,concept_dimension,N,20\n
2,\\PCORI\\PROCEDURE\\CH\\,9,Leaf,Active,N,concept_dimension,N,687\n
2,\\PCORI\\PROCEDURE\\CH\\,9,Leaf,Active,Y,concept_dimension,N,2973\n
2,\\PCORI\\PROCEDURE\\CH\\,10,Leaf,Active,N,concept_dimension,N,79\n
2,\\PCORI\\PROCEDURE\\CH\\,10,Leaf,Active,Y,concept_dimension,N,849\n
2,\\PCORI\\PROCEDURE\\LC\\,,,,,,,\n
2,\\PCORI\\PROCEDURE\\n
D\\,,,,,,,\n
2,\\PCORI\\PROCEDURE\\RE\\,,,,,,,\n
2,\\PCORI\\PROCEDURE\\VERSION\\,,,,,,,\n
1,\\PCORI\\VITAL\\,2,Folder,Active,N,concept_dimension,N,2\n
1,\\PCORI\\VITAL\\,2,Leaf,Active,N,concept_dimension,Y,3\n
1,\\PCORI\\VITAL\\,2,Leaf,Hidden,N,concept_dimension,Y,4\n
1,\\PCORI\\VITAL\\,2,Leaf,Inactive,N,concept_dimension,N,1\n
1,\\PCORI\\VITAL\\,3,Case,Active,N,concept_dimension,N,2\n
1,\\PCORI\\VITAL\\,3,Folder,Active,N,concept_dimension,N,1\n
1,\\PCORI\\VITAL\\,3,Leaf,Active,N,concept_dimension,N,2\n
1,\\PCORI\\VITAL\\,3,Leaf,Active,N,concept_dimension,Y,2\n
1,\\PCORI\\VITAL\\,3,Leaf,Inactive,N,concept_dimension,N,1\n
1,\\PCORI\\VITAL\\,4,Folder,Active,N,concept_dimension,N,1\n
1,\\PCORI\\VITAL\\,4,Leaf,Active,N,concept_dimension,N,6\n
1,\\PCORI\\VITAL\\,4,Leaf,Hidden,N,concept_dimension,N,1\n
1,\\PCORI\\VITAL\\,5,Leaf,Active,N,concept_dimension,N,5\n
2,\\PCORI\\VITAL\\BP\\,3,Leaf,Active,N,concept_dimension,Y,2\n
2,\\PCORI\\VITAL\\HT\\,,,,,,,\n
2,\\PCORI\\VITAL\\ORIGINAL_BMI\\,,,,,,,\n
2,\\PCORI\\VITAL\\RAW_BP_POSITION\\,,,,,,,\n
2,\\PCORI\\VITAL\\RAW_DIASTOLIC\\,,,,,,,\n
2,\\PCORI\\VITAL\\RAW_SYSTOLIC\\,,,,,,,\n
2,\\PCORI\\VITAL\\RAW_VITAL_SOURCE\\,,,,,,,\n
2,\\PCORI\\VITAL\\TOBACCO\\,3,Case,Active,N,concept_dimension,N,2\n
2,\\PCORI\\VITAL\\TOBACCO\\,3,Folder,Active,N,concept_dimension,N,1\n
2,\\PCORI\\VITAL\\TOBACCO\\,3,Leaf,Active,N,concept_dimension,N,2\n
2,\\PCORI\\VITAL\\TOBACCO\\,3,Leaf,Inactive,N,concept_dimension,N,1\n
2,\\PCORI\\VITAL\\TOBACCO\\,4,Folder,Active,N,concept_dimension,N,1\n
2,\\PCORI\\VITAL\\TOBACCO\\,4,Leaf,Active,N,concept_dimension,N,6\n
2,\\PCORI\\VITAL\\TOBACCO\\,4,Leaf,Hidden,N,concept_dimension,N,1\n
2,\\PCORI\\VITAL\\TOBACCO\\,5,Leaf,Active,N,concept_dimension,N,5\n
2,\\PCORI\\VITAL\\VERSION\\,,,,,,,\n
2,\\PCORI\\VITAL\\WT\\,,,,,,,\n
`;

export const subtreeBreakdown = vegaRead(subtreeBreakdownCsv, {
  type: 'csv',
  parse: {
    NodeLevel: 'integer',
    SubtreeLevel: 'integer',
    NumberOfPaths: 'integer'
  }
}).filter((item) => {
  return item.NodeLevel != null && !Number.isNaN(item.NodeLevel);
});
