export const subtreeBreakdownCsv =
`NodeLevel,NodePath,SubtreeLevel,ConceptType,Visibility,IsSynonym,TableName,HasMetadataXML,NumberOfPaths
0,\\PCORI\\,1,Case,Active,N,concept_dimension,N,6
0,\\PCORI\\,1,Case,Active,N,concept_dimension,Y,1
0,\\PCORI\\,1,Case,Active,N,patient_dimension,N,1
0,\\PCORI\\,2,Case,Active,N,concept_dimension,N,9
0,\\PCORI\\,2,Case,Active,N,patient_dimension,N,3
0,\\PCORI\\,2,Case,Active,N,patient_dimension,Y,1
0,\\PCORI\\,2,Case,Active,N,visit_dimension,N,1
0,\\PCORI\\,2,Folder,Active,N,concept_dimension,N,7
0,\\PCORI\\,2,Folder,Active,N,patient_dimension,N,1
0,\\PCORI\\,2,Folder,Inactive,N,concept_dimension,N,6
0,\\PCORI\\,2,Leaf,Active,N,concept_dimension,Y,3
0,\\PCORI\\,2,Leaf,Hidden,N,concept_dimension,Y,23
0,\\PCORI\\,2,Leaf,Hidden,N,visit_dimension,Y,9
0,\\PCORI\\,2,Leaf,Inactive,N,concept_dimension,N,7
0,\\PCORI\\,2,Leaf,Inactive,N,visit_dimension,N,1
0,\\PCORI\\,2,Leaf,Inactive,N,visit_dimension,Y,2
0,\\PCORI\\,3,Case,Active,N,concept_dimension,N,47
0,\\PCORI\\,3,Folder,Active,N,concept_dimension,N,62
0,\\PCORI\\,3,Folder,Active,N,concept_dimension,Y,1
0,\\PCORI\\,3,Folder,Active,N,patient_dimension,N,10
0,\\PCORI\\,3,Folder,Active,N,visit_dimension,N,72
0,\\PCORI\\,3,Leaf,Active,N,concept_dimension,N,4
0,\\PCORI\\,3,Leaf,Active,N,concept_dimension,Y,2
0,\\PCORI\\,3,Leaf,Active,N,patient_dimension,N,23
0,\\PCORI\\,3,Leaf,Active,N,visit_dimension,N,43
0,\\PCORI\\,3,Leaf,Hidden,N,patient_dimension,N,1
0,\\PCORI\\,3,Leaf,Inactive,N,concept_dimension,N,2
0,\\PCORI\\,3,Leaf,Inactive,N,observation_fact,N,3
0,\\PCORI\\,3,Leaf,Inactive,N,patient_dimension,N,1
0,\\PCORI\\,3,Leaf,Inactive,N,visit_dimension,N,4
0,\\PCORI\\,4,Folder,Active,N,concept_dimension,N,1280
0,\\PCORI\\,4,Folder,Active,N,concept_dimension,Y,1
0,\\PCORI\\,4,Folder,Active,N,patient_dimension,N,3
0,\\PCORI\\,4,Folder,Active,Y,concept_dimension,N,92
0,\\PCORI\\,4,Folder,Inactive,N,concept_dimension,N,1
0,\\PCORI\\,4,Leaf,Active,N,concept_dimension,N,242
0,\\PCORI\\,4,Leaf,Active,N,concept_dimension,Y,4
0,\\PCORI\\,4,Leaf,Active,N,patient_dimension,N,107
0,\\PCORI\\,4,Leaf,Active,N,visit_dimension,N,1047
0,\\PCORI\\,4,Leaf,Active,Y,concept_dimension,N,143
0,\\PCORI\\,4,Leaf,Hidden,N,concept_dimension,N,1
0,\\PCORI\\,4,Leaf,Inactive,N,concept_dimension,N,82
0,\\PCORI\\,4,Leaf,Inactive,N,patient_dimension,N,67
0,\\PCORI\\,5,Folder,Active,N,concept_dimension,N,9270
0,\\PCORI\\,5,Folder,Active,N,concept_dimension,Y,69
0,\\PCORI\\,5,Folder,Active,N,patient_dimension,N,3
0,\\PCORI\\,5,Folder,Active,Y,concept_dimension,N,2882
0,\\PCORI\\,5,Folder,Hidden,N,concept_dimension,Y,1
0,\\PCORI\\,5,Folder,Inactive,N,concept_dimension,N,3
0,\\PCORI\\,5,Folder,Inactive,N,concept_dimension,Y,5
0,\\PCORI\\,5,Leaf,Active,N,concept_dimension,N,12023
0,\\PCORI\\,5,Leaf,Active,N,concept_dimension,Y,1
0,\\PCORI\\,5,Leaf,Active,N,patient_dimension,N,34
0,\\PCORI\\,5,Leaf,Active,Y,concept_dimension,N,4694
0,\\PCORI\\,5,Leaf,Active,Y,concept_dimension,Y,3
0,\\PCORI\\,5,Leaf,Inactive,N,concept_dimension,N,119
0,\\PCORI\\,5,Leaf,Inactive,Y,concept_dimension,N,66
0,\\PCORI\\,6,Folder,Active,N,concept_dimension,N,32678
0,\\PCORI\\,6,Folder,Active,N,concept_dimension,Y,1
0,\\PCORI\\,6,Folder,Active,Y,concept_dimension,N,4067
0,\\PCORI\\,6,Folder,Inactive,N,concept_dimension,N,1
0,\\PCORI\\,6,Leaf,Active,N,concept_dimension,N,36983
0,\\PCORI\\,6,Leaf,Active,N,concept_dimension,Y,268
0,\\PCORI\\,6,Leaf,Active,N,patient_dimension,N,94
0,\\PCORI\\,6,Leaf,Active,Y,concept_dimension,N,14475
0,\\PCORI\\,6,Leaf,Active,Y,concept_dimension,Y,258
0,\\PCORI\\,6,Leaf,Hidden,N,concept_dimension,Y,6
0,\\PCORI\\,6,Leaf,Hidden,Y,concept_dimension,Y,19
0,\\PCORI\\,6,Leaf,Inactive,N,concept_dimension,N,1396
0,\\PCORI\\,6,Leaf,Inactive,N,concept_dimension,Y,38
0,\\PCORI\\,6,Leaf,Inactive,Y,concept_dimension,N,2496
0,\\PCORI\\,6,Leaf,Inactive,Y,concept_dimension,Y,63
0,\\PCORI\\,7,Folder,Active,N,concept_dimension,N,56970
0,\\PCORI\\,7,Folder,Active,Y,concept_dimension,N,2249
0,\\PCORI\\,7,Leaf,Active,N,concept_dimension,N,74511
0,\\PCORI\\,7,Leaf,Active,N,concept_dimension,Y,9
0,\\PCORI\\,7,Leaf,Active,Y,concept_dimension,N,15713
0,\\PCORI\\,7,Leaf,Active,Y,concept_dimension,Y,54
0,\\PCORI\\,7,Leaf,Inactive,N,concept_dimension,N,6559
0,\\PCORI\\,7,Leaf,Inactive,Y,concept_dimension,N,23440
0,\\PCORI\\,8,Folder,Active,N,concept_dimension,N,73938
0,\\PCORI\\,8,Folder,Active,Y,concept_dimension,N,632
0,\\PCORI\\,8,Leaf,Active,N,concept_dimension,N,65790
0,\\PCORI\\,8,Leaf,Active,Y,concept_dimension,N,18628
0,\\PCORI\\,8,Leaf,Inactive,N,concept_dimension,N,5993
0,\\PCORI\\,8,Leaf,Inactive,Y,concept_dimension,N,9969
0,\\PCORI\\,9,Folder,Active,N,concept_dimension,N,102
0,\\PCORI\\,9,Folder,Active,Y,concept_dimension,N,20
0,\\PCORI\\,9,Leaf,Active,N,concept_dimension,N,111697
0,\\PCORI\\,9,Leaf,Active,Y,concept_dimension,N,146821
0,\\PCORI\\,9,Leaf,Inactive,N,concept_dimension,N,4508
0,\\PCORI\\,9,Leaf,Inactive,Y,concept_dimension,N,7211
0,\\PCORI\\,10,Leaf,Active,N,concept_dimension,N,79
0,\\PCORI\\,10,Leaf,Active,Y,concept_dimension,N,849
0,\\PCORI\\,10,Leaf,Inactive,N,concept_dimension,N,6944
0,\\PCORI\\,10,Leaf,Inactive,Y,concept_dimension,N,9544
0,\\PCORI\\,11,Leaf,Inactive,N,concept_dimension,N,19
1,\\PCORI\\DEMOGRAPHIC\\,2,Case,Active,N,patient_dimension,N,3
1,\\PCORI\\DEMOGRAPHIC\\,2,Case,Active,N,patient_dimension,Y,1
1,\\PCORI\\DEMOGRAPHIC\\,2,Folder,Active,N,patient_dimension,N,1
1,\\PCORI\\DEMOGRAPHIC\\,2,Leaf,Hidden,N,concept_dimension,Y,5
1,\\PCORI\\DEMOGRAPHIC\\,2,Leaf,Inactive,N,concept_dimension,N,1
1,\\PCORI\\DEMOGRAPHIC\\,3,Folder,Active,N,patient_dimension,N,10
1,\\PCORI\\DEMOGRAPHIC\\,3,Leaf,Active,N,patient_dimension,N,23
1,\\PCORI\\DEMOGRAPHIC\\,3,Leaf,Hidden,N,patient_dimension,N,1
1,\\PCORI\\DEMOGRAPHIC\\,3,Leaf,Inactive,N,patient_dimension,N,1
1,\\PCORI\\DEMOGRAPHIC\\,4,Folder,Active,N,patient_dimension,N,3
1,\\PCORI\\DEMOGRAPHIC\\,4,Leaf,Active,N,patient_dimension,N,107
1,\\PCORI\\DEMOGRAPHIC\\,4,Leaf,Inactive,N,patient_dimension,N,67
1,\\PCORI\\DEMOGRAPHIC\\,5,Folder,Active,N,patient_dimension,N,3
1,\\PCORI\\DEMOGRAPHIC\\,5,Leaf,Active,N,patient_dimension,N,34
1,\\PCORI\\DEMOGRAPHIC\\,6,Leaf,Active,N,patient_dimension,N,94
2,\\PCORI\\DEMOGRAPHIC\\Age\\,3,Folder,Active,N,patient_dimension,N,10
2,\\PCORI\\DEMOGRAPHIC\\Age\\,3,Leaf,Active,N,patient_dimension,N,1
2,\\PCORI\\DEMOGRAPHIC\\Age\\,4,Folder,Active,N,patient_dimension,N,3
2,\\PCORI\\DEMOGRAPHIC\\Age\\,4,Leaf,Active,N,patient_dimension,N,107
2,\\PCORI\\DEMOGRAPHIC\\Age\\,4,Leaf,Inactive,N,patient_dimension,N,67
2,\\PCORI\\DEMOGRAPHIC\\Age\\,5,Folder,Active,N,patient_dimension,N,3
2,\\PCORI\\DEMOGRAPHIC\\Age\\,5,Leaf,Active,N,patient_dimension,N,34
2,\\PCORI\\DEMOGRAPHIC\\Age\\,6,Leaf,Active,N,patient_dimension,N,94
2,\\PCORI\\DEMOGRAPHIC\\BIOBANK_FLAG\\,3,Leaf,Active,N,patient_dimension,N,1
2,\\PCORI\\DEMOGRAPHIC\\BIOBANK_FLAG\\,3,Leaf,Hidden,N,patient_dimension,N,1
2,\\PCORI\\DEMOGRAPHIC\\BIRTH_DATE\\,,,,,,,
2,\\PCORI\\DEMOGRAPHIC\\BIRTH_TIME\\,,,,,,,
2,\\PCORI\\DEMOGRAPHIC\\HISPANIC\\,3,Leaf,Active,N,patient_dimension,N,5
2,\\PCORI\\DEMOGRAPHIC\\HISPANIC\\,3,Leaf,Inactive,N,patient_dimension,N,1
2,\\PCORI\\DEMOGRAPHIC\\RACE\\,3,Leaf,Active,N,patient_dimension,N,10
2,\\PCORI\\DEMOGRAPHIC\\RAW_HISPANIC\\,,,,,,,
2,\\PCORI\\DEMOGRAPHIC\\RAW_RACE\\,,,,,,,
2,\\PCORI\\DEMOGRAPHIC\\RAW_SEX\\,,,,,,,
2,\\PCORI\\DEMOGRAPHIC\\SEX\\,3,Leaf,Active,N,patient_dimension,N,6
2,\\PCORI\\DEMOGRAPHIC\\VERSION\\,,,,,,,
1,\\PCORI\\DIAGNOSIS\\,2,Case,Active,N,concept_dimension,N,1
1,\\PCORI\\DIAGNOSIS\\,2,Folder,Active,N,concept_dimension,N,1
1,\\PCORI\\DIAGNOSIS\\,2,Folder,Inactive,N,concept_dimension,N,2
1,\\PCORI\\DIAGNOSIS\\,2,Leaf,Hidden,N,concept_dimension,Y,4
1,\\PCORI\\DIAGNOSIS\\,2,Leaf,Inactive,N,concept_dimension,N,1
1,\\PCORI\\DIAGNOSIS\\,3,Case,Active,N,concept_dimension,N,21
1,\\PCORI\\DIAGNOSIS\\,3,Folder,Active,N,concept_dimension,N,3
1,\\PCORI\\DIAGNOSIS\\,4,Folder,Active,N,concept_dimension,N,334
1,\\PCORI\\DIAGNOSIS\\,4,Folder,Active,Y,concept_dimension,N,92
1,\\PCORI\\DIAGNOSIS\\,4,Leaf,Active,N,concept_dimension,N,1
1,\\PCORI\\DIAGNOSIS\\,4,Leaf,Inactive,N,concept_dimension,N,3
1,\\PCORI\\DIAGNOSIS\\,5,Folder,Active,N,concept_dimension,N,2185
1,\\PCORI\\DIAGNOSIS\\,5,Folder,Active,Y,concept_dimension,N,1128
1,\\PCORI\\DIAGNOSIS\\,5,Leaf,Active,N,concept_dimension,N,136
1,\\PCORI\\DIAGNOSIS\\,5,Leaf,Active,Y,concept_dimension,N,56
1,\\PCORI\\DIAGNOSIS\\,5,Leaf,Inactive,N,concept_dimension,N,108
1,\\PCORI\\DIAGNOSIS\\,5,Leaf,Inactive,Y,concept_dimension,N,66
1,\\PCORI\\DIAGNOSIS\\,6,Folder,Active,N,concept_dimension,N,7857
1,\\PCORI\\DIAGNOSIS\\,6,Folder,Active,Y,concept_dimension,N,3960
1,\\PCORI\\DIAGNOSIS\\,6,Leaf,Active,N,concept_dimension,N,4800
1,\\PCORI\\DIAGNOSIS\\,6,Leaf,Active,Y,concept_dimension,N,1963
1,\\PCORI\\DIAGNOSIS\\,6,Leaf,Inactive,N,concept_dimension,N,1396
1,\\PCORI\\DIAGNOSIS\\,6,Leaf,Inactive,Y,concept_dimension,N,2486
1,\\PCORI\\DIAGNOSIS\\,7,Folder,Active,N,concept_dimension,N,9596
1,\\PCORI\\DIAGNOSIS\\,7,Folder,Active,Y,concept_dimension,N,2114
1,\\PCORI\\DIAGNOSIS\\,7,Leaf,Active,N,concept_dimension,N,13401
1,\\PCORI\\DIAGNOSIS\\,7,Leaf,Active,Y,concept_dimension,N,1050
1,\\PCORI\\DIAGNOSIS\\,7,Leaf,Inactive,N,concept_dimension,N,6559
1,\\PCORI\\DIAGNOSIS\\,7,Leaf,Inactive,Y,concept_dimension,N,23440
1,\\PCORI\\DIAGNOSIS\\,8,Folder,Active,N,concept_dimension,N,9513
1,\\PCORI\\DIAGNOSIS\\,8,Folder,Active,Y,concept_dimension,N,592
1,\\PCORI\\DIAGNOSIS\\,8,Leaf,Active,N,concept_dimension,N,22945
1,\\PCORI\\DIAGNOSIS\\,8,Leaf,Active,Y,concept_dimension,N,498
1,\\PCORI\\DIAGNOSIS\\,8,Leaf,Inactive,N,concept_dimension,N,5993
1,\\PCORI\\DIAGNOSIS\\,8,Leaf,Inactive,Y,concept_dimension,N,9969
1,\\PCORI\\DIAGNOSIS\\,9,Folder,Active,N,concept_dimension,N,61
1,\\PCORI\\DIAGNOSIS\\,9,Leaf,Active,N,concept_dimension,N,39047
1,\\PCORI\\DIAGNOSIS\\,9,Leaf,Inactive,N,concept_dimension,N,4508
1,\\PCORI\\DIAGNOSIS\\,9,Leaf,Inactive,Y,concept_dimension,N,7211
1,\\PCORI\\DIAGNOSIS\\,10,Leaf,Inactive,N,concept_dimension,N,6944
1,\\PCORI\\DIAGNOSIS\\,10,Leaf,Inactive,Y,concept_dimension,N,9544
1,\\PCORI\\DIAGNOSIS\\,11,Leaf,Inactive,N,concept_dimension,N,19
2,\\PCORI\\DIAGNOSIS\\09\\,3,Folder,Active,N,concept_dimension,N,3
2,\\PCORI\\DIAGNOSIS\\09\\,4,Folder,Active,N,concept_dimension,N,55
2,\\PCORI\\DIAGNOSIS\\09\\,4,Leaf,Active,N,concept_dimension,N,1
2,\\PCORI\\DIAGNOSIS\\09\\,5,Folder,Active,N,concept_dimension,N,364
2,\\PCORI\\DIAGNOSIS\\09\\,5,Leaf,Active,N,concept_dimension,N,54
2,\\PCORI\\DIAGNOSIS\\09\\,6,Folder,Active,N,concept_dimension,N,1036
2,\\PCORI\\DIAGNOSIS\\09\\,6,Leaf,Active,N,concept_dimension,N,1597
2,\\PCORI\\DIAGNOSIS\\09\\,7,Folder,Active,N,concept_dimension,N,1591
2,\\PCORI\\DIAGNOSIS\\09\\,7,Leaf,Active,N,concept_dimension,N,4882
2,\\PCORI\\DIAGNOSIS\\09\\,8,Folder,Active,N,concept_dimension,N,145
2,\\PCORI\\DIAGNOSIS\\09\\,8,Leaf,Active,N,concept_dimension,N,7268
2,\\PCORI\\DIAGNOSIS\\09\\,9,Leaf,Active,N,concept_dimension,N,867
2,\\PCORI\\DIAGNOSIS\\10\\,3,Case,Active,N,concept_dimension,N,21
2,\\PCORI\\DIAGNOSIS\\10\\,4,Folder,Active,N,concept_dimension,N,279
2,\\PCORI\\DIAGNOSIS\\10\\,4,Folder,Active,Y,concept_dimension,N,92
2,\\PCORI\\DIAGNOSIS\\10\\,4,Leaf,Inactive,N,concept_dimension,N,3
2,\\PCORI\\DIAGNOSIS\\10\\,5,Folder,Active,N,concept_dimension,N,1821
2,\\PCORI\\DIAGNOSIS\\10\\,5,Folder,Active,Y,concept_dimension,N,1128
2,\\PCORI\\DIAGNOSIS\\10\\,5,Leaf,Active,N,concept_dimension,N,82
2,\\PCORI\\DIAGNOSIS\\10\\,5,Leaf,Active,Y,concept_dimension,N,56
2,\\PCORI\\DIAGNOSIS\\10\\,5,Leaf,Inactive,N,concept_dimension,N,108
2,\\PCORI\\DIAGNOSIS\\10\\,5,Leaf,Inactive,Y,concept_dimension,N,66
2,\\PCORI\\DIAGNOSIS\\10\\,6,Folder,Active,N,concept_dimension,N,6821
2,\\PCORI\\DIAGNOSIS\\10\\,6,Folder,Active,Y,concept_dimension,N,3960
2,\\PCORI\\DIAGNOSIS\\10\\,6,Leaf,Active,N,concept_dimension,N,3203
2,\\PCORI\\DIAGNOSIS\\10\\,6,Leaf,Active,Y,concept_dimension,N,1963
2,\\PCORI\\DIAGNOSIS\\10\\,6,Leaf,Inactive,N,concept_dimension,N,1396
2,\\PCORI\\DIAGNOSIS\\10\\,6,Leaf,Inactive,Y,concept_dimension,N,2486
2,\\PCORI\\DIAGNOSIS\\10\\,7,Folder,Active,N,concept_dimension,N,8005
2,\\PCORI\\DIAGNOSIS\\10\\,7,Folder,Active,Y,concept_dimension,N,2114
2,\\PCORI\\DIAGNOSIS\\10\\,7,Leaf,Active,N,concept_dimension,N,8519
2,\\PCORI\\DIAGNOSIS\\10\\,7,Leaf,Active,Y,concept_dimension,N,1050
2,\\PCORI\\DIAGNOSIS\\10\\,7,Leaf,Inactive,N,concept_dimension,N,6559
2,\\PCORI\\DIAGNOSIS\\10\\,7,Leaf,Inactive,Y,concept_dimension,N,23440
2,\\PCORI\\DIAGNOSIS\\10\\,8,Folder,Active,N,concept_dimension,N,9368
2,\\PCORI\\DIAGNOSIS\\10\\,8,Folder,Active,Y,concept_dimension,N,592
2,\\PCORI\\DIAGNOSIS\\10\\,8,Leaf,Active,N,concept_dimension,N,15677
2,\\PCORI\\DIAGNOSIS\\10\\,8,Leaf,Active,Y,concept_dimension,N,498
2,\\PCORI\\DIAGNOSIS\\10\\,8,Leaf,Inactive,N,concept_dimension,N,5993
2,\\PCORI\\DIAGNOSIS\\10\\,8,Leaf,Inactive,Y,concept_dimension,N,9969
2,\\PCORI\\DIAGNOSIS\\10\\,9,Folder,Active,N,concept_dimension,N,61
2,\\PCORI\\DIAGNOSIS\\10\\,9,Leaf,Active,N,concept_dimension,N,38180
2,\\PCORI\\DIAGNOSIS\\10\\,9,Leaf,Inactive,N,concept_dimension,N,4508
2,\\PCORI\\DIAGNOSIS\\10\\,9,Leaf,Inactive,Y,concept_dimension,N,7211
2,\\PCORI\\DIAGNOSIS\\10\\,10,Leaf,Inactive,N,concept_dimension,N,6944
2,\\PCORI\\DIAGNOSIS\\10\\,10,Leaf,Inactive,Y,concept_dimension,N,9544
2,\\PCORI\\DIAGNOSIS\\10\\,11,Leaf,Inactive,N,concept_dimension,N,19
2,\\PCORI\\DIAGNOSIS\\11\\,,,,,,,
2,\\PCORI\\DIAGNOSIS\\RAW_DX\\,,,,,,,
2,\\PCORI\\DIAGNOSIS\\RAW_DX_SOURCE\\,,,,,,,
2,\\PCORI\\DIAGNOSIS\\RAW_DX_TYPE\\,,,,,,,
2,\\PCORI\\DIAGNOSIS\\RAW_PDX\\,,,,,,,
2,\\PCORI\\DIAGNOSIS\\SM\\,,,,,,,
2,\\PCORI\\DIAGNOSIS\\VERSION\\,,,,,,,
1,\\PCORI\\ENCOUNTER\\,2,Case,Active,N,concept_dimension,N,5
1,\\PCORI\\ENCOUNTER\\,2,Case,Active,N,visit_dimension,N,1
1,\\PCORI\\ENCOUNTER\\,2,Folder,Active,N,concept_dimension,N,1
1,\\PCORI\\ENCOUNTER\\,2,Leaf,Hidden,N,visit_dimension,Y,9
1,\\PCORI\\ENCOUNTER\\,2,Leaf,Inactive,N,visit_dimension,N,1
1,\\PCORI\\ENCOUNTER\\,2,Leaf,Inactive,N,visit_dimension,Y,2
1,\\PCORI\\ENCOUNTER\\,3,Folder,Active,N,concept_dimension,N,2
1,\\PCORI\\ENCOUNTER\\,3,Folder,Active,N,visit_dimension,N,72
1,\\PCORI\\ENCOUNTER\\,3,Leaf,Active,N,concept_dimension,N,2
1,\\PCORI\\ENCOUNTER\\,3,Leaf,Active,N,visit_dimension,N,42
1,\\PCORI\\ENCOUNTER\\,3,Leaf,Inactive,N,concept_dimension,N,1
1,\\PCORI\\ENCOUNTER\\,3,Leaf,Inactive,N,visit_dimension,N,4
1,\\PCORI\\ENCOUNTER\\,4,Folder,Active,N,concept_dimension,N,54
1,\\PCORI\\ENCOUNTER\\,4,Leaf,Active,N,visit_dimension,N,1047
1,\\PCORI\\ENCOUNTER\\,5,Folder,Active,N,concept_dimension,N,51
1,\\PCORI\\ENCOUNTER\\,5,Leaf,Active,N,concept_dimension,N,749
1,\\PCORI\\ENCOUNTER\\,6,Folder,Active,N,concept_dimension,N,2
1,\\PCORI\\ENCOUNTER\\,6,Leaf,Active,N,concept_dimension,N,659
1,\\PCORI\\ENCOUNTER\\,7,Leaf,Active,N,concept_dimension,N,4
2,\\PCORI\\ENCOUNTER\\ADMIT_DATE\\,,,,,,,
2,\\PCORI\\ENCOUNTER\\ADMIT_TIME\\,,,,,,,
2,\\PCORI\\ENCOUNTER\\ADMITTING_SOURCE\\,3,Leaf,Active,N,visit_dimension,N,14
2,\\PCORI\\ENCOUNTER\\ADMITTING_SOURCE\\,3,Leaf,Inactive,N,visit_dimension,N,1
2,\\PCORI\\ENCOUNTER\\Age at visit\\,3,Folder,Active,N,visit_dimension,N,10
2,\\PCORI\\ENCOUNTER\\Age at visit\\,4,Leaf,Active,N,visit_dimension,N,110
2,\\PCORI\\ENCOUNTER\\DISCHARGE_DATE\\,,,,,,,
2,\\PCORI\\ENCOUNTER\\DISCHARGE_DISPOSITION\\,3,Leaf,Active,N,visit_dimension,N,4
2,\\PCORI\\ENCOUNTER\\DISCHARGE_DISPOSITION\\,3,Leaf,Inactive,N,visit_dimension,N,1
2,\\PCORI\\ENCOUNTER\\DISCHARGE_STATUS\\,3,Leaf,Active,N,visit_dimension,N,16
2,\\PCORI\\ENCOUNTER\\DISCHARGE_STATUS\\,3,Leaf,Inactive,N,visit_dimension,N,1
2,\\PCORI\\ENCOUNTER\\DISCHARGE_TIME\\,,,,,,,
2,\\PCORI\\ENCOUNTER\\DRG\\,3,Folder,Active,N,concept_dimension,N,2
2,\\PCORI\\ENCOUNTER\\DRG\\,3,Leaf,Active,N,concept_dimension,N,2
2,\\PCORI\\ENCOUNTER\\DRG\\,3,Leaf,Inactive,N,concept_dimension,N,1
2,\\PCORI\\ENCOUNTER\\DRG\\,4,Folder,Active,N,concept_dimension,N,54
2,\\PCORI\\ENCOUNTER\\DRG\\,5,Folder,Active,N,concept_dimension,N,51
2,\\PCORI\\ENCOUNTER\\DRG\\,5,Leaf,Active,N,concept_dimension,N,749
2,\\PCORI\\ENCOUNTER\\DRG\\,6,Folder,Active,N,concept_dimension,N,2
2,\\PCORI\\ENCOUNTER\\DRG\\,6,Leaf,Active,N,concept_dimension,N,659
2,\\PCORI\\ENCOUNTER\\DRG\\,7,Leaf,Active,N,concept_dimension,N,4
2,\\PCORI\\ENCOUNTER\\ENC_TYPE\\,3,Leaf,Active,N,visit_dimension,N,8
2,\\PCORI\\ENCOUNTER\\ENC_TYPE\\,3,Leaf,Inactive,N,visit_dimension,N,1
2,\\PCORI\\ENCOUNTER\\FACILITY_LOCATION\\,3,Folder,Active,N,visit_dimension,N,62
2,\\PCORI\\ENCOUNTER\\FACILITY_LOCATION\\,4,Leaf,Active,N,visit_dimension,N,937
2,\\PCORI\\ENCOUNTER\\FACILITYID\\,,,,,,,
2,\\PCORI\\ENCOUNTER\\PROVIDERID\\,,,,,,,
2,\\PCORI\\ENCOUNTER\\RAW_ADMITTING_SOURCE\\,,,,,,,
2,\\PCORI\\ENCOUNTER\\RAW_DISCHARGE_DISPOSITION\\,,,,,,,
2,\\PCORI\\ENCOUNTER\\RAW_DISCHARGE_STATUS\\,,,,,,,
2,\\PCORI\\ENCOUNTER\\RAW_DRG_TYPE\\,,,,,,,
2,\\PCORI\\ENCOUNTER\\RAW_ENC_TYPE\\,,,,,,,
2,\\PCORI\\ENCOUNTER\\VERSION\\,,,,,,,
1,\\PCORI\\ENROLLMENT\\,2,Case,Active,N,concept_dimension,N,1
1,\\PCORI\\ENROLLMENT\\,2,Leaf,Hidden,N,concept_dimension,Y,2
1,\\PCORI\\ENROLLMENT\\,2,Leaf,Inactive,N,concept_dimension,N,1
1,\\PCORI\\ENROLLMENT\\,3,Leaf,Active,N,visit_dimension,N,1
1,\\PCORI\\ENROLLMENT\\,3,Leaf,Inactive,N,observation_fact,N,3
2,\\PCORI\\ENROLLMENT\\ENR_BASIS\\,3,Leaf,Active,N,visit_dimension,N,1
2,\\PCORI\\ENROLLMENT\\ENR_BASIS\\,3,Leaf,Inactive,N,observation_fact,N,3
2,\\PCORI\\ENROLLMENT\\ENR_END_DATE\\,,,,,,,
2,\\PCORI\\ENROLLMENT\\ENR_START_DATE\\,,,,,,,
2,\\PCORI\\ENROLLMENT\\VERSION\\,,,,,,,
1,\\PCORI\\LAB_RESULT_CM\\,2,Folder,Active,N,concept_dimension,N,1
1,\\PCORI\\LAB_RESULT_CM\\,2,Leaf,Inactive,N,concept_dimension,N,1
1,\\PCORI\\LAB_RESULT_CM\\,3,Folder,Active,N,concept_dimension,N,5
1,\\PCORI\\LAB_RESULT_CM\\,3,Folder,Active,N,concept_dimension,Y,1
1,\\PCORI\\LAB_RESULT_CM\\,4,Folder,Active,N,concept_dimension,N,17
1,\\PCORI\\LAB_RESULT_CM\\,4,Folder,Active,N,concept_dimension,Y,1
1,\\PCORI\\LAB_RESULT_CM\\,4,Folder,Inactive,N,concept_dimension,N,1
1,\\PCORI\\LAB_RESULT_CM\\,4,Leaf,Active,N,concept_dimension,Y,4
1,\\PCORI\\LAB_RESULT_CM\\,5,Folder,Active,N,concept_dimension,N,3
1,\\PCORI\\LAB_RESULT_CM\\,5,Folder,Active,N,concept_dimension,Y,69
1,\\PCORI\\LAB_RESULT_CM\\,5,Folder,Hidden,N,concept_dimension,Y,1
1,\\PCORI\\LAB_RESULT_CM\\,5,Folder,Inactive,N,concept_dimension,N,3
1,\\PCORI\\LAB_RESULT_CM\\,5,Folder,Inactive,N,concept_dimension,Y,5
1,\\PCORI\\LAB_RESULT_CM\\,5,Leaf,Active,N,concept_dimension,Y,1
1,\\PCORI\\LAB_RESULT_CM\\,5,Leaf,Active,Y,concept_dimension,Y,3
1,\\PCORI\\LAB_RESULT_CM\\,6,Folder,Active,N,concept_dimension,N,8
1,\\PCORI\\LAB_RESULT_CM\\,6,Folder,Active,N,concept_dimension,Y,1
1,\\PCORI\\LAB_RESULT_CM\\,6,Leaf,Active,N,concept_dimension,N,46
1,\\PCORI\\LAB_RESULT_CM\\,6,Leaf,Active,N,concept_dimension,Y,268
1,\\PCORI\\LAB_RESULT_CM\\,6,Leaf,Active,Y,concept_dimension,N,46
1,\\PCORI\\LAB_RESULT_CM\\,6,Leaf,Active,Y,concept_dimension,Y,258
1,\\PCORI\\LAB_RESULT_CM\\,6,Leaf,Hidden,N,concept_dimension,Y,6
1,\\PCORI\\LAB_RESULT_CM\\,6,Leaf,Hidden,Y,concept_dimension,Y,19
1,\\PCORI\\LAB_RESULT_CM\\,6,Leaf,Inactive,N,concept_dimension,Y,38
1,\\PCORI\\LAB_RESULT_CM\\,6,Leaf,Inactive,Y,concept_dimension,N,10
1,\\PCORI\\LAB_RESULT_CM\\,6,Leaf,Inactive,Y,concept_dimension,Y,63
1,\\PCORI\\LAB_RESULT_CM\\,7,Leaf,Active,N,concept_dimension,N,16
1,\\PCORI\\LAB_RESULT_CM\\,7,Leaf,Active,N,concept_dimension,Y,9
1,\\PCORI\\LAB_RESULT_CM\\,7,Leaf,Active,Y,concept_dimension,N,135
1,\\PCORI\\LAB_RESULT_CM\\,7,Leaf,Active,Y,concept_dimension,Y,54
2,\\PCORI\\LAB_RESULT_CM\\LAB_NAME\\,3,Folder,Active,N,concept_dimension,N,5
2,\\PCORI\\LAB_RESULT_CM\\LAB_NAME\\,3,Folder,Active,N,concept_dimension,Y,1
2,\\PCORI\\LAB_RESULT_CM\\LAB_NAME\\,4,Folder,Active,N,concept_dimension,N,17
2,\\PCORI\\LAB_RESULT_CM\\LAB_NAME\\,4,Folder,Active,N,concept_dimension,Y,1
2,\\PCORI\\LAB_RESULT_CM\\LAB_NAME\\,4,Folder,Inactive,N,concept_dimension,N,1
2,\\PCORI\\LAB_RESULT_CM\\LAB_NAME\\,4,Leaf,Active,N,concept_dimension,Y,4
2,\\PCORI\\LAB_RESULT_CM\\LAB_NAME\\,5,Folder,Active,N,concept_dimension,N,3
2,\\PCORI\\LAB_RESULT_CM\\LAB_NAME\\,5,Folder,Active,N,concept_dimension,Y,69
2,\\PCORI\\LAB_RESULT_CM\\LAB_NAME\\,5,Folder,Hidden,N,concept_dimension,Y,1
2,\\PCORI\\LAB_RESULT_CM\\LAB_NAME\\,5,Folder,Inactive,N,concept_dimension,N,3
2,\\PCORI\\LAB_RESULT_CM\\LAB_NAME\\,5,Folder,Inactive,N,concept_dimension,Y,5
2,\\PCORI\\LAB_RESULT_CM\\LAB_NAME\\,5,Leaf,Active,N,concept_dimension,Y,1
2,\\PCORI\\LAB_RESULT_CM\\LAB_NAME\\,5,Leaf,Active,Y,concept_dimension,Y,3
2,\\PCORI\\LAB_RESULT_CM\\LAB_NAME\\,6,Folder,Active,N,concept_dimension,N,8
2,\\PCORI\\LAB_RESULT_CM\\LAB_NAME\\,6,Folder,Active,N,concept_dimension,Y,1
2,\\PCORI\\LAB_RESULT_CM\\LAB_NAME\\,6,Leaf,Active,N,concept_dimension,N,46
2,\\PCORI\\LAB_RESULT_CM\\LAB_NAME\\,6,Leaf,Active,N,concept_dimension,Y,268
2,\\PCORI\\LAB_RESULT_CM\\LAB_NAME\\,6,Leaf,Active,Y,concept_dimension,N,46
2,\\PCORI\\LAB_RESULT_CM\\LAB_NAME\\,6,Leaf,Active,Y,concept_dimension,Y,258
2,\\PCORI\\LAB_RESULT_CM\\LAB_NAME\\,6,Leaf,Hidden,N,concept_dimension,Y,6
2,\\PCORI\\LAB_RESULT_CM\\LAB_NAME\\,6,Leaf,Hidden,Y,concept_dimension,Y,19
2,\\PCORI\\LAB_RESULT_CM\\LAB_NAME\\,6,Leaf,Inactive,N,concept_dimension,Y,38
2,\\PCORI\\LAB_RESULT_CM\\LAB_NAME\\,6,Leaf,Inactive,Y,concept_dimension,N,10
2,\\PCORI\\LAB_RESULT_CM\\LAB_NAME\\,6,Leaf,Inactive,Y,concept_dimension,Y,63
2,\\PCORI\\LAB_RESULT_CM\\LAB_NAME\\,7,Leaf,Active,N,concept_dimension,N,16
2,\\PCORI\\LAB_RESULT_CM\\LAB_NAME\\,7,Leaf,Active,N,concept_dimension,Y,9
2,\\PCORI\\LAB_RESULT_CM\\LAB_NAME\\,7,Leaf,Active,Y,concept_dimension,N,135
2,\\PCORI\\LAB_RESULT_CM\\LAB_NAME\\,7,Leaf,Active,Y,concept_dimension,Y,54
2,\\PCORI\\LAB_RESULT_CM\\VERSION\\,,,,,,,
1,\\PCORI\\MEDICATION\\,2,Case,Active,N,concept_dimension,N,1
1,\\PCORI\\MEDICATION\\,2,Leaf,Hidden,N,concept_dimension,Y,8
1,\\PCORI\\MEDICATION\\,2,Leaf,Inactive,N,concept_dimension,N,1
1,\\PCORI\\MEDICATION\\,3,Folder,Active,N,concept_dimension,N,32
1,\\PCORI\\MEDICATION\\,4,Folder,Active,N,concept_dimension,N,475
1,\\PCORI\\MEDICATION\\,4,Leaf,Active,N,concept_dimension,N,125
1,\\PCORI\\MEDICATION\\,4,Leaf,Inactive,N,concept_dimension,N,79
1,\\PCORI\\MEDICATION\\,5,Folder,Active,N,concept_dimension,N,4860
1,\\PCORI\\MEDICATION\\,5,Leaf,Active,N,concept_dimension,N,8557
1,\\PCORI\\MEDICATION\\,5,Leaf,Inactive,N,concept_dimension,N,11
1,\\PCORI\\MEDICATION\\,6,Folder,Active,N,concept_dimension,N,12462
1,\\PCORI\\MEDICATION\\,6,Folder,Inactive,N,concept_dimension,N,1
1,\\PCORI\\MEDICATION\\,6,Leaf,Active,N,concept_dimension,N,22543
1,\\PCORI\\MEDICATION\\,7,Folder,Active,N,concept_dimension,N,13296
1,\\PCORI\\MEDICATION\\,7,Leaf,Active,N,concept_dimension,N,56253
1,\\PCORI\\MEDICATION\\,8,Folder,Active,N,concept_dimension,N,2962
1,\\PCORI\\MEDICATION\\,8,Leaf,Active,N,concept_dimension,N,38995
1,\\PCORI\\MEDICATION\\,9,Leaf,Active,N,concept_dimension,N,39
2,\\PCORI\\MEDICATION\\RAW_RX_FREQUENCY\\,,,,,,,
2,\\PCORI\\MEDICATION\\RAW_RX_MED_NAME\\,,,,,,,
2,\\PCORI\\MEDICATION\\RAW_RXNORM_CUI\\,,,,,,,
2,\\PCORI\\MEDICATION\\RX_END_DATE\\,,,,,,,
2,\\PCORI\\MEDICATION\\RX_ORDER_DATE\\,,,,,,,
2,\\PCORI\\MEDICATION\\RX_ORDER_TIME\\,,,,,,,
2,\\PCORI\\MEDICATION\\RX_PROVIDERID\\,,,,,,,
2,\\PCORI\\MEDICATION\\RX_START_DATE\\,,,,,,,
2,\\PCORI\\MEDICATION\\RXNORM_CUI\\,3,Folder,Active,N,concept_dimension,N,32
2,\\PCORI\\MEDICATION\\RXNORM_CUI\\,4,Folder,Active,N,concept_dimension,N,475
2,\\PCORI\\MEDICATION\\RXNORM_CUI\\,4,Leaf,Active,N,concept_dimension,N,125
2,\\PCORI\\MEDICATION\\RXNORM_CUI\\,4,Leaf,Inactive,N,concept_dimension,N,79
2,\\PCORI\\MEDICATION\\RXNORM_CUI\\,5,Folder,Active,N,concept_dimension,N,4860
2,\\PCORI\\MEDICATION\\RXNORM_CUI\\,5,Leaf,Active,N,concept_dimension,N,8557
2,\\PCORI\\MEDICATION\\RXNORM_CUI\\,5,Leaf,Inactive,N,concept_dimension,N,11
2,\\PCORI\\MEDICATION\\RXNORM_CUI\\,6,Folder,Active,N,concept_dimension,N,12462
2,\\PCORI\\MEDICATION\\RXNORM_CUI\\,6,Folder,Inactive,N,concept_dimension,N,1
2,\\PCORI\\MEDICATION\\RXNORM_CUI\\,6,Leaf,Active,N,concept_dimension,N,22543
2,\\PCORI\\MEDICATION\\RXNORM_CUI\\,7,Folder,Active,N,concept_dimension,N,13296
2,\\PCORI\\MEDICATION\\RXNORM_CUI\\,7,Leaf,Active,N,concept_dimension,N,56253
2,\\PCORI\\MEDICATION\\RXNORM_CUI\\,8,Folder,Active,N,concept_dimension,N,2962
2,\\PCORI\\MEDICATION\\RXNORM_CUI\\,8,Leaf,Active,N,concept_dimension,N,38995
2,\\PCORI\\MEDICATION\\RXNORM_CUI\\,9,Leaf,Active,N,concept_dimension,N,39
2,\\PCORI\\MEDICATION\\VERSION\\,,,,,,,
1,\\PCORI\\PROCEDURE\\,2,Case,Active,N,concept_dimension,N,1
1,\\PCORI\\PROCEDURE\\,2,Folder,Active,N,concept_dimension,N,2
1,\\PCORI\\PROCEDURE\\,2,Folder,Inactive,N,concept_dimension,N,4
1,\\PCORI\\PROCEDURE\\,2,Leaf,Inactive,N,concept_dimension,N,1
1,\\PCORI\\PROCEDURE\\,3,Case,Active,N,concept_dimension,N,24
1,\\PCORI\\PROCEDURE\\,3,Folder,Active,N,concept_dimension,N,19
1,\\PCORI\\PROCEDURE\\,4,Folder,Active,N,concept_dimension,N,399
1,\\PCORI\\PROCEDURE\\,4,Leaf,Active,N,concept_dimension,N,110
1,\\PCORI\\PROCEDURE\\,4,Leaf,Active,Y,concept_dimension,N,143
1,\\PCORI\\PROCEDURE\\,5,Folder,Active,N,concept_dimension,N,2171
1,\\PCORI\\PROCEDURE\\,5,Folder,Active,Y,concept_dimension,N,1754
1,\\PCORI\\PROCEDURE\\,5,Leaf,Active,N,concept_dimension,N,2576
1,\\PCORI\\PROCEDURE\\,5,Leaf,Active,Y,concept_dimension,N,4638
1,\\PCORI\\PROCEDURE\\,6,Folder,Active,N,concept_dimension,N,12349
1,\\PCORI\\PROCEDURE\\,6,Folder,Active,Y,concept_dimension,N,107
1,\\PCORI\\PROCEDURE\\,6,Leaf,Active,N,concept_dimension,N,8935
1,\\PCORI\\PROCEDURE\\,6,Leaf,Active,Y,concept_dimension,N,12466
1,\\PCORI\\PROCEDURE\\,7,Folder,Active,N,concept_dimension,N,34078
1,\\PCORI\\PROCEDURE\\,7,Folder,Active,Y,concept_dimension,N,135
1,\\PCORI\\PROCEDURE\\,7,Leaf,Active,N,concept_dimension,N,4837
1,\\PCORI\\PROCEDURE\\,7,Leaf,Active,Y,concept_dimension,N,14528
1,\\PCORI\\PROCEDURE\\,8,Folder,Active,N,concept_dimension,N,61463
1,\\PCORI\\PROCEDURE\\,8,Folder,Active,Y,concept_dimension,N,40
1,\\PCORI\\PROCEDURE\\,8,Leaf,Active,N,concept_dimension,N,3850
1,\\PCORI\\PROCEDURE\\,8,Leaf,Active,Y,concept_dimension,N,18130
1,\\PCORI\\PROCEDURE\\,9,Folder,Active,N,concept_dimension,N,41
1,\\PCORI\\PROCEDURE\\,9,Folder,Active,Y,concept_dimension,N,20
1,\\PCORI\\PROCEDURE\\,9,Leaf,Active,N,concept_dimension,N,72611
1,\\PCORI\\PROCEDURE\\,9,Leaf,Active,Y,concept_dimension,N,146821
1,\\PCORI\\PROCEDURE\\,10,Leaf,Active,N,concept_dimension,N,79
1,\\PCORI\\PROCEDURE\\,10,Leaf,Active,Y,concept_dimension,N,849
2,\\PCORI\\PROCEDURE\\09\\,3,Folder,Active,N,concept_dimension,N,18
2,\\PCORI\\PROCEDURE\\09\\,4,Folder,Active,N,concept_dimension,N,109
2,\\PCORI\\PROCEDURE\\09\\,5,Folder,Active,N,concept_dimension,N,659
2,\\PCORI\\PROCEDURE\\09\\,5,Leaf,Active,N,concept_dimension,N,295
2,\\PCORI\\PROCEDURE\\09\\,6,Leaf,Active,N,concept_dimension,N,3583
2,\\PCORI\\PROCEDURE\\10\\,3,Case,Active,N,concept_dimension,N,16
2,\\PCORI\\PROCEDURE\\10\\,4,Folder,Active,N,concept_dimension,N,102
2,\\PCORI\\PROCEDURE\\10\\,5,Folder,Active,N,concept_dimension,N,845
2,\\PCORI\\PROCEDURE\\10\\,5,Folder,Active,Y,concept_dimension,N,1690
2,\\PCORI\\PROCEDURE\\10\\,6,Folder,Active,N,concept_dimension,N,11304
2,\\PCORI\\PROCEDURE\\10\\,7,Folder,Active,N,concept_dimension,N,32727
2,\\PCORI\\PROCEDURE\\10\\,8,Folder,Active,N,concept_dimension,N,61271
2,\\PCORI\\PROCEDURE\\10\\,9,Leaf,Active,N,concept_dimension,N,71924
2,\\PCORI\\PROCEDURE\\10\\,9,Leaf,Active,Y,concept_dimension,N,143848
2,\\PCORI\\PROCEDURE\\11\\,,,,,,,
2,\\PCORI\\PROCEDURE\\CH\\,3,Case,Active,N,concept_dimension,N,8
2,\\PCORI\\PROCEDURE\\CH\\,3,Folder,Active,N,concept_dimension,N,1
2,\\PCORI\\PROCEDURE\\CH\\,4,Folder,Active,N,concept_dimension,N,188
2,\\PCORI\\PROCEDURE\\CH\\,4,Leaf,Active,N,concept_dimension,N,110
2,\\PCORI\\PROCEDURE\\CH\\,4,Leaf,Active,Y,concept_dimension,N,143
2,\\PCORI\\PROCEDURE\\CH\\,5,Folder,Active,N,concept_dimension,N,667
2,\\PCORI\\PROCEDURE\\CH\\,5,Folder,Active,Y,concept_dimension,N,64
2,\\PCORI\\PROCEDURE\\CH\\,5,Leaf,Active,N,concept_dimension,N,2281
2,\\PCORI\\PROCEDURE\\CH\\,5,Leaf,Active,Y,concept_dimension,N,4638
2,\\PCORI\\PROCEDURE\\CH\\,6,Folder,Active,N,concept_dimension,N,1045
2,\\PCORI\\PROCEDURE\\CH\\,6,Folder,Active,Y,concept_dimension,N,107
2,\\PCORI\\PROCEDURE\\CH\\,6,Leaf,Active,N,concept_dimension,N,5352
2,\\PCORI\\PROCEDURE\\CH\\,6,Leaf,Active,Y,concept_dimension,N,12466
2,\\PCORI\\PROCEDURE\\CH\\,7,Folder,Active,N,concept_dimension,N,1351
2,\\PCORI\\PROCEDURE\\CH\\,7,Folder,Active,Y,concept_dimension,N,135
2,\\PCORI\\PROCEDURE\\CH\\,7,Leaf,Active,N,concept_dimension,N,4837
2,\\PCORI\\PROCEDURE\\CH\\,7,Leaf,Active,Y,concept_dimension,N,14528
2,\\PCORI\\PROCEDURE\\CH\\,8,Folder,Active,N,concept_dimension,N,192
2,\\PCORI\\PROCEDURE\\CH\\,8,Folder,Active,Y,concept_dimension,N,40
2,\\PCORI\\PROCEDURE\\CH\\,8,Leaf,Active,N,concept_dimension,N,3850
2,\\PCORI\\PROCEDURE\\CH\\,8,Leaf,Active,Y,concept_dimension,N,18130
2,\\PCORI\\PROCEDURE\\CH\\,9,Folder,Active,N,concept_dimension,N,41
2,\\PCORI\\PROCEDURE\\CH\\,9,Folder,Active,Y,concept_dimension,N,20
2,\\PCORI\\PROCEDURE\\CH\\,9,Leaf,Active,N,concept_dimension,N,687
2,\\PCORI\\PROCEDURE\\CH\\,9,Leaf,Active,Y,concept_dimension,N,2973
2,\\PCORI\\PROCEDURE\\CH\\,10,Leaf,Active,N,concept_dimension,N,79
2,\\PCORI\\PROCEDURE\\CH\\,10,Leaf,Active,Y,concept_dimension,N,849
2,\\PCORI\\PROCEDURE\\LC\\,,,,,,,
2,\\PCORI\\PROCEDURE\\D\\,,,,,,,
2,\\PCORI\\PROCEDURE\\RE\\,,,,,,,
2,\\PCORI\\PROCEDURE\\VERSION\\,,,,,,,
1,\\PCORI\\VITAL\\,2,Folder,Active,N,concept_dimension,N,2
1,\\PCORI\\VITAL\\,2,Leaf,Active,N,concept_dimension,Y,3
1,\\PCORI\\VITAL\\,2,Leaf,Hidden,N,concept_dimension,Y,4
1,\\PCORI\\VITAL\\,2,Leaf,Inactive,N,concept_dimension,N,1
1,\\PCORI\\VITAL\\,3,Case,Active,N,concept_dimension,N,2
1,\\PCORI\\VITAL\\,3,Folder,Active,N,concept_dimension,N,1
1,\\PCORI\\VITAL\\,3,Leaf,Active,N,concept_dimension,N,2
1,\\PCORI\\VITAL\\,3,Leaf,Active,N,concept_dimension,Y,2
1,\\PCORI\\VITAL\\,3,Leaf,Inactive,N,concept_dimension,N,1
1,\\PCORI\\VITAL\\,4,Folder,Active,N,concept_dimension,N,1
1,\\PCORI\\VITAL\\,4,Leaf,Active,N,concept_dimension,N,6
1,\\PCORI\\VITAL\\,4,Leaf,Hidden,N,concept_dimension,N,1
1,\\PCORI\\VITAL\\,5,Leaf,Active,N,concept_dimension,N,5
2,\\PCORI\\VITAL\\BP\\,3,Leaf,Active,N,concept_dimension,Y,2
2,\\PCORI\\VITAL\\HT\\,,,,,,,
2,\\PCORI\\VITAL\\ORIGINAL_BMI\\,,,,,,,
2,\\PCORI\\VITAL\\RAW_BP_POSITION\\,,,,,,,
2,\\PCORI\\VITAL\\RAW_DIASTOLIC\\,,,,,,,
2,\\PCORI\\VITAL\\RAW_SYSTOLIC\\,,,,,,,
2,\\PCORI\\VITAL\\RAW_VITAL_SOURCE\\,,,,,,,
2,\\PCORI\\VITAL\\TOBACCO\\,3,Case,Active,N,concept_dimension,N,2
2,\\PCORI\\VITAL\\TOBACCO\\,3,Folder,Active,N,concept_dimension,N,1
2,\\PCORI\\VITAL\\TOBACCO\\,3,Leaf,Active,N,concept_dimension,N,2
2,\\PCORI\\VITAL\\TOBACCO\\,3,Leaf,Inactive,N,concept_dimension,N,1
2,\\PCORI\\VITAL\\TOBACCO\\,4,Folder,Active,N,concept_dimension,N,1
2,\\PCORI\\VITAL\\TOBACCO\\,4,Leaf,Active,N,concept_dimension,N,6
2,\\PCORI\\VITAL\\TOBACCO\\,4,Leaf,Hidden,N,concept_dimension,N,1
2,\\PCORI\\VITAL\\TOBACCO\\,5,Leaf,Active,N,concept_dimension,N,5
2,\\PCORI\\VITAL\\VERSION\\,,,,,,,
2,\\PCORI\\VITAL\\WT\\,,,,,,,`;
